#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_plugins.earlybound
{
	
	
	/// <summary>
	/// Tipo de usuário.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum systemuser_accessmode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeituraGravao = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Administrativo = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Leitura = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SuporteaoUsurio = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoInterativo = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AdministradorDelegado = 5,
	}
	
	/// <summary>
	/// Tipo do endereço 1, como por exemplo, endereço para cobrança, endereço para entrega ou endereço primário.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum systemuser_address1_addresstypecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ValorPadro = 1,
	}
	
	/// <summary>
	/// Método de entrega para endereço 1.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum systemuser_address1_shippingmethodcode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ValorPadro = 1,
	}
	
	/// <summary>
	/// Tipo do endereço 2, como por exemplo, endereço para cobrança, endereço para entrega ou endereço primário.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum systemuser_address2_addresstypecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ValorPadro = 1,
	}
	
	/// <summary>
	/// Método de entrega para endereço 2.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum systemuser_address2_shippingmethodcode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ValorPadro = 1,
	}
	
	/// <summary>
	/// Estado do usuário do Azure.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum systemuser_azurestate
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Existe = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Excludotemporariamente = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Noencontradoouexcludopermanentemente = 2,
	}
	
	/// <summary>
	/// Tipo de licença do usuário. Isso é usado somente na versão local do produto. As licenças online são gerenciadas por meio do Portal do Microsoft 365 Office.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum systemuser_caltype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Profissional = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Administrativo = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Bsico = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProfissionaldeDispositivo = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DispositivoBsico = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Essencial = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DispositivoEssencial = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Empresa = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmpresadeDispositivos = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Vendas = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Servio = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FieldService = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProjectService = 12,
	}
	
	/// <summary>
	/// Estado de exclusão do usuário.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum systemuser_deletestate
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Noexcludo = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Exclusoreversvel = 1,
	}
	
	/// <summary>
	/// Indica as opções de aprovação de acesso para sincronização no servidor ou E-mail Router.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum systemuser_emailrouteraccessapproval
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Vazio = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Aprovado = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AprovaoPendente = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Rejeitado = 3,
	}
	
	/// <summary>
	/// Método de entrega de emails de entrada do usuário.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum systemuser_incomingemaildeliverymethod
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Nenhum = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftDynamics365paraOutlook = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SincronizaonoServidorouEmailRouter = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CaixadeCorreioparaEncaminhamento = 3,
	}
	
	/// <summary>
	/// Status do convite do usuário.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum systemuser_invitestatuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConvitenoEnviado = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Convidado = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConviteQuaseVencido = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConviteVencido = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConviteAceito = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConviteRecusado = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConviteRevogado = 6,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_systemuser_msdyn_agentType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Usuriodeaplicativo = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Usuriodeaplicativodebot = 192350001,
	}
	
	/// <summary>
	/// Indica o tipo de bot
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_systemuser_msdyn_botprovider
	{
		
		/// <summary>
		/// CCI first party Bot
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgenteVirtual = 192350000,
		
		/// <summary>
		/// Other type of bot
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Outros = 192350001,
		
		/// <summary>
		/// Indicates that the user is not a bot
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Nenhum = 192350002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_systemuser_msdyn_usertype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UsuriodoCRM = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UsuriodoBOT = 192350001,
	}
	
	/// <summary>
	/// Método de entrega de emails de saída do usuário.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum systemuser_outgoingemaildeliverymethod
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Nenhum = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftDynamics365paraOutlook = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SincronizaonoServidorouEmailRouter = 2,
	}
	
	/// <summary>
	/// Endereço preferencial do usuário.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum systemuser_preferredaddresscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EndereoparaCorrespondncia = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OutroEndereo = 2,
	}
	
	/// <summary>
	/// Endereço de email preferencial do usuário.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum systemuser_preferredemailcode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ValorPadro = 1,
	}
	
	/// <summary>
	/// Número de telefone preferencial do usuário.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum systemuser_preferredphonecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TelefonePrincipal = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OutroTelefone = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TelefoneResidencial = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TelefoneCelular = 4,
	}
	
	/// <summary>
	/// O tipo de usuário
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum systemuser_systemmanagedusertype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UsuriodoEntra = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UsuriodoC2 = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImpersonableStubUser = 2,
	}
	
	/// <summary>
	/// Pessoa com acesso ao sistema Microsoft CRM e proprietária de objetos no banco de dados do Microsoft CRM.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("systemuser")]
	public partial class SystemUser : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the systemuser entity
		/// </summary>
		public partial class Fields
		{
			public const string AccessMode = "accessmode";
			public const string Address1_AddressId = "address1_addressid";
			public const string Address1_AddressTypeCode = "address1_addresstypecode";
			public const string Address1_City = "address1_city";
			public const string Address1_Composite = "address1_composite";
			public const string Address1_Country = "address1_country";
			public const string Address1_County = "address1_county";
			public const string Address1_Fax = "address1_fax";
			public const string Address1_Latitude = "address1_latitude";
			public const string Address1_Line1 = "address1_line1";
			public const string Address1_Line2 = "address1_line2";
			public const string Address1_Line3 = "address1_line3";
			public const string Address1_Longitude = "address1_longitude";
			public const string Address1_Name = "address1_name";
			public const string Address1_PostalCode = "address1_postalcode";
			public const string Address1_PostOfficeBox = "address1_postofficebox";
			public const string Address1_ShippingMethodCode = "address1_shippingmethodcode";
			public const string Address1_StateOrProvince = "address1_stateorprovince";
			public const string Address1_Telephone1 = "address1_telephone1";
			public const string Address1_Telephone2 = "address1_telephone2";
			public const string Address1_Telephone3 = "address1_telephone3";
			public const string Address1_UPSZone = "address1_upszone";
			public const string Address1_UTCOffset = "address1_utcoffset";
			public const string Address2_AddressId = "address2_addressid";
			public const string Address2_AddressTypeCode = "address2_addresstypecode";
			public const string Address2_City = "address2_city";
			public const string Address2_Composite = "address2_composite";
			public const string Address2_Country = "address2_country";
			public const string Address2_County = "address2_county";
			public const string Address2_Fax = "address2_fax";
			public const string Address2_Latitude = "address2_latitude";
			public const string Address2_Line1 = "address2_line1";
			public const string Address2_Line2 = "address2_line2";
			public const string Address2_Line3 = "address2_line3";
			public const string Address2_Longitude = "address2_longitude";
			public const string Address2_Name = "address2_name";
			public const string Address2_PostalCode = "address2_postalcode";
			public const string Address2_PostOfficeBox = "address2_postofficebox";
			public const string Address2_ShippingMethodCode = "address2_shippingmethodcode";
			public const string Address2_StateOrProvince = "address2_stateorprovince";
			public const string Address2_Telephone1 = "address2_telephone1";
			public const string Address2_Telephone2 = "address2_telephone2";
			public const string Address2_Telephone3 = "address2_telephone3";
			public const string Address2_UPSZone = "address2_upszone";
			public const string Address2_UTCOffset = "address2_utcoffset";
			public const string ApplicationId = "applicationid";
			public const string ApplicationIdUri = "applicationiduri";
			public const string AzureActiveDirectoryObjectId = "azureactivedirectoryobjectid";
			public const string AzureDeletedOn = "azuredeletedon";
			public const string AzureState = "azurestate";
			public const string BusinessUnitId = "businessunitid";
			public const string CalendarId = "calendarid";
			public const string CALType = "caltype";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string DefaultFiltersPopulated = "defaultfilterspopulated";
			public const string DefaultMailbox = "defaultmailbox";
			public const string DefaultOdbFolderName = "defaultodbfoldername";
			public const string DeletedState = "deletedstate";
			public const string DisabledReason = "disabledreason";
			public const string DisplayInServiceViews = "displayinserviceviews";
			public const string DomainName = "domainname";
			public const string EmailRouterAccessApproval = "emailrouteraccessapproval";
			public const string EmployeeId = "employeeid";
			public const string EntityImage = "entityimage";
			public const string EntityImage_Timestamp = "entityimage_timestamp";
			public const string EntityImage_URL = "entityimage_url";
			public const string EntityImageId = "entityimageid";
			public const string ExchangeRate = "exchangerate";
			public const string FirstName = "firstname";
			public const string FullName = "fullname";
			public const string GovernmentId = "governmentid";
			public const string HomePhone = "homephone";
			public const string i4d_email_contato = "i4d_email_contato";
			public const string i4d_positionheld = "i4d_positionheld";
			public const string IdentityId = "identityid";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string IncomingEmailDeliveryMethod = "incomingemaildeliverymethod";
			public const string InternalEMailAddress = "internalemailaddress";
			public const string InviteStatusCode = "invitestatuscode";
			public const string IsAllowedByIpFirewall = "isallowedbyipfirewall";
			public const string IsDisabled = "isdisabled";
			public const string IsEmailAddressApprovedByO365Admin = "isemailaddressapprovedbyo365admin";
			public const string IsIntegrationUser = "isintegrationuser";
			public const string IsLicensed = "islicensed";
			public const string IsSyncWithDirectory = "issyncwithdirectory";
			public const string JobTitle = "jobtitle";
			public const string LastName = "lastname";
			public const string MiddleName = "middlename";
			public const string MobileAlertEMail = "mobilealertemail";
			public const string MobileOfflineProfileId = "mobileofflineprofileid";
			public const string MobilePhone = "mobilephone";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string msdyn_AgentType = "msdyn_agentType";
			public const string msdyn_BotApplicationId = "msdyn_botapplicationid";
			public const string msdyn_BotDescription = "msdyn_botdescription";
			public const string msdyn_BotEndpoint = "msdyn_botendpoint";
			public const string msdyn_bothandle = "msdyn_bothandle";
			public const string msdyn_BotProvider = "msdyn_botprovider";
			public const string msdyn_BotSecretKeys = "msdyn_botsecretkeys";
			public const string msdyn_Capacity = "msdyn_capacity";
			public const string msdyn_DefaultPresenceIdUser = "msdyn_defaultpresenceiduser";
			public const string msdyn_gdproptout = "msdyn_gdproptout";
			public const string msdyn_gridwrappercontrolfield = "msdyn_gridwrappercontrolfield";
			public const string msdyn_isexpertenabledforswarm = "msdyn_isexpertenabledforswarm";
			public const string msdyn_OwningEnvironmentId = "msdyn_owningenvironmentid";
			public const string msdyn_UserType = "msdyn_usertype";
			public const string NickName = "nickname";
			public const string OrganizationId = "organizationid";
			public const string OutgoingEmailDeliveryMethod = "outgoingemaildeliverymethod";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string ParentSystemUserId = "parentsystemuserid";
			public const string PassportHi = "passporthi";
			public const string PassportLo = "passportlo";
			public const string PersonalEMailAddress = "personalemailaddress";
			public const string PhotoUrl = "photourl";
			public const string PositionId = "positionid";
			public const string PreferredAddressCode = "preferredaddresscode";
			public const string PreferredEmailCode = "preferredemailcode";
			public const string PreferredPhoneCode = "preferredphonecode";
			public const string ProcessId = "processid";
			public const string QueueId = "queueid";
			public const string Salutation = "salutation";
			public const string SetupUser = "setupuser";
			public const string SharePointEmailAddress = "sharepointemailaddress";
			public const string SiteId = "siteid";
			public const string Skills = "skills";
			public const string StageId = "stageid";
			public const string SystemManagedUserType = "systemmanagedusertype";
			public const string SystemUserId = "systemuserid";
			public const string Id = "systemuserid";
			public const string TerritoryId = "territoryid";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string Title = "title";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string TraversedPath = "traversedpath";
			public const string UserLicenseType = "userlicensetype";
			public const string UserPuid = "userpuid";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string WindowsLiveID = "windowsliveid";
			public const string YammerEmailAddress = "yammeremailaddress";
			public const string YammerUserId = "yammeruserid";
			public const string YomiFirstName = "yomifirstname";
			public const string YomiFullName = "yomifullname";
			public const string YomiLastName = "yomilastname";
			public const string YomiMiddleName = "yomimiddlename";
			public const string lk_businessunit_createdonbehalfby = "lk_businessunit_createdonbehalfby";
			public const string lk_businessunit_modifiedonbehalfby = "lk_businessunit_modifiedonbehalfby";
			public const string lk_businessunitbase_createdby = "lk_businessunitbase_createdby";
			public const string lk_businessunitbase_modifiedby = "lk_businessunitbase_modifiedby";
			public const string lk_opportunity_createdonbehalfby = "lk_opportunity_createdonbehalfby";
			public const string lk_opportunity_modifiedonbehalfby = "lk_opportunity_modifiedonbehalfby";
			public const string lk_opportunitybase_createdby = "lk_opportunitybase_createdby";
			public const string lk_opportunitybase_modifiedby = "lk_opportunitybase_modifiedby";
			public const string lk_opportunityproduct_createdonbehalfby = "lk_opportunityproduct_createdonbehalfby";
			public const string lk_opportunityproduct_modifiedonbehalfby = "lk_opportunityproduct_modifiedonbehalfby";
			public const string lk_opportunityproductbase_createdby = "lk_opportunityproductbase_createdby";
			public const string lk_opportunityproductbase_modifiedby = "lk_opportunityproductbase_modifiedby";
			public const string lk_organization_createdonbehalfby = "lk_organization_createdonbehalfby";
			public const string lk_organization_modifiedonbehalfby = "lk_organization_modifiedonbehalfby";
			public const string lk_organizationbase_createdby = "lk_organizationbase_createdby";
			public const string lk_organizationbase_modifiedby = "lk_organizationbase_modifiedby";
			public const string lk_quote_createdonbehalfby = "lk_quote_createdonbehalfby";
			public const string lk_quote_modifiedonbehalfby = "lk_quote_modifiedonbehalfby";
			public const string lk_quotebase_createdby = "lk_quotebase_createdby";
			public const string lk_quotebase_modifiedby = "lk_quotebase_modifiedby";
			public const string lk_role_createdonbehalfby = "lk_role_createdonbehalfby";
			public const string lk_role_modifiedonbehalfby = "lk_role_modifiedonbehalfby";
			public const string lk_rolebase_createdby = "lk_rolebase_createdby";
			public const string lk_rolebase_modifiedby = "lk_rolebase_modifiedby";
			public const string lk_salesorder_createdonbehalfby = "lk_salesorder_createdonbehalfby";
			public const string lk_salesorder_modifiedonbehalfby = "lk_salesorder_modifiedonbehalfby";
			public const string lk_salesorderbase_createdby = "lk_salesorderbase_createdby";
			public const string lk_salesorderbase_modifiedby = "lk_salesorderbase_modifiedby";
			public const string Referencedlk_systemuser_createdonbehalfby = "Referencedlk_systemuser_createdonbehalfby";
			public const string Referencedlk_systemuser_modifiedonbehalfby = "Referencedlk_systemuser_modifiedonbehalfby";
			public const string Referencedlk_systemuserbase_createdby = "Referencedlk_systemuserbase_createdby";
			public const string Referencedlk_systemuserbase_modifiedby = "Referencedlk_systemuserbase_modifiedby";
			public const string lk_team_createdonbehalfby = "lk_team_createdonbehalfby";
			public const string lk_team_modifiedonbehalfby = "lk_team_modifiedonbehalfby";
			public const string lk_teambase_administratorid = "lk_teambase_administratorid";
			public const string lk_teambase_createdby = "lk_teambase_createdby";
			public const string lk_teambase_modifiedby = "lk_teambase_modifiedby";
			public const string lk_usersettings_createdonbehalfby = "lk_usersettings_createdonbehalfby";
			public const string lk_usersettings_modifiedonbehalfby = "lk_usersettings_modifiedonbehalfby";
			public const string lk_usersettingsbase_createdby = "lk_usersettingsbase_createdby";
			public const string lk_usersettingsbase_modifiedby = "lk_usersettingsbase_modifiedby";
			public const string lk_webresourcebase_createdonbehalfby = "lk_webresourcebase_createdonbehalfby";
			public const string lk_webresourcebase_modifiedonbehalfby = "lk_webresourcebase_modifiedonbehalfby";
			public const string opportunity_owning_user = "opportunity_owning_user";
			public const string system_user_orders = "system_user_orders";
			public const string system_user_quotes = "system_user_quotes";
			public const string user_opportunityproduct = "user_opportunityproduct";
			public const string Referenceduser_parent_user = "Referenceduser_parent_user";
			public const string user_settings = "user_settings";
			public const string webresource_createdby = "webresource_createdby";
			public const string webresource_modifiedby = "webresource_modifiedby";
			public const string systemuserroles_association = "systemuserroles_association";
			public const string teammembership_association = "teammembership_association";
			public const string business_unit_system_users = "business_unit_system_users";
			public const string Referencinglk_systemuser_createdonbehalfby = "lk_systemuser_createdonbehalfby";
			public const string Referencinglk_systemuser_modifiedonbehalfby = "lk_systemuser_modifiedonbehalfby";
			public const string Referencinglk_systemuserbase_createdby = "lk_systemuserbase_createdby";
			public const string Referencinglk_systemuserbase_modifiedby = "lk_systemuserbase_modifiedby";
			public const string organization_system_users = "organization_system_users";
			public const string Referencinguser_parent_user = "user_parent_user";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public SystemUser() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "systemuser";
		
		public const string EntityLogicalCollectionName = "systemusers";
		
		public const string EntitySetName = "systemusers";
		
		/// <summary>
		/// Tipo de usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("accessmode")]
		public virtual systemuser_accessmode? AccessMode
		{
			get
			{
				return ((systemuser_accessmode?)(EntityOptionSetEnum.GetEnum(this, "accessmode")));
			}
			set
			{
				this.SetAttributeValue("accessmode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do endereço 1.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address1_addressid")]
		public System.Nullable<System.Guid> Address1_AddressId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("address1_addressid");
			}
			set
			{
				this.SetAttributeValue("address1_addressid", value);
			}
		}
		
		/// <summary>
		/// Tipo do endereço 1, como por exemplo, endereço para cobrança, endereço para entrega ou endereço primário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address1_addresstypecode")]
		public virtual systemuser_address1_addresstypecode? Address1_AddressTypeCode
		{
			get
			{
				return ((systemuser_address1_addresstypecode?)(EntityOptionSetEnum.GetEnum(this, "address1_addresstypecode")));
			}
			set
			{
				this.SetAttributeValue("address1_addresstypecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Nome da cidade do endereço 1.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address1_city")]
		public string Address1_City
		{
			get
			{
				return this.GetAttributeValue<string>("address1_city");
			}
			set
			{
				this.SetAttributeValue("address1_city", value);
			}
		}
		
		/// <summary>
		/// Mostra o endereço principal completo.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address1_composite")]
		public string Address1_Composite
		{
			get
			{
				return this.GetAttributeValue<string>("address1_composite");
			}
		}
		
		/// <summary>
		/// Nome do país/região em endereço 1.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address1_country")]
		public string Address1_Country
		{
			get
			{
				return this.GetAttributeValue<string>("address1_country");
			}
			set
			{
				this.SetAttributeValue("address1_country", value);
			}
		}
		
		/// <summary>
		/// Nome do município do endereço 1.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address1_county")]
		public string Address1_County
		{
			get
			{
				return this.GetAttributeValue<string>("address1_county");
			}
			set
			{
				this.SetAttributeValue("address1_county", value);
			}
		}
		
		/// <summary>
		/// Número de fax do endereço 1.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address1_fax")]
		public string Address1_Fax
		{
			get
			{
				return this.GetAttributeValue<string>("address1_fax");
			}
			set
			{
				this.SetAttributeValue("address1_fax", value);
			}
		}
		
		/// <summary>
		/// Latitude do endereço 1.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address1_latitude")]
		public System.Nullable<double> Address1_Latitude
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("address1_latitude");
			}
			set
			{
				this.SetAttributeValue("address1_latitude", value);
			}
		}
		
		/// <summary>
		/// Primeira linha para inserir informações de endereço 1.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address1_line1")]
		public string Address1_Line1
		{
			get
			{
				return this.GetAttributeValue<string>("address1_line1");
			}
			set
			{
				this.SetAttributeValue("address1_line1", value);
			}
		}
		
		/// <summary>
		/// Segunda linha para inserir informações de endereço 1.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address1_line2")]
		public string Address1_Line2
		{
			get
			{
				return this.GetAttributeValue<string>("address1_line2");
			}
			set
			{
				this.SetAttributeValue("address1_line2", value);
			}
		}
		
		/// <summary>
		/// Terceira linha para inserir informações de endereço 1.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address1_line3")]
		public string Address1_Line3
		{
			get
			{
				return this.GetAttributeValue<string>("address1_line3");
			}
			set
			{
				this.SetAttributeValue("address1_line3", value);
			}
		}
		
		/// <summary>
		/// Longitude do endereço 1.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address1_longitude")]
		public System.Nullable<double> Address1_Longitude
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("address1_longitude");
			}
			set
			{
				this.SetAttributeValue("address1_longitude", value);
			}
		}
		
		/// <summary>
		/// Nome a ser inserido para endereço 1.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address1_name")]
		public string Address1_Name
		{
			get
			{
				return this.GetAttributeValue<string>("address1_name");
			}
			set
			{
				this.SetAttributeValue("address1_name", value);
			}
		}
		
		/// <summary>
		/// CEP do endereço 1.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address1_postalcode")]
		public string Address1_PostalCode
		{
			get
			{
				return this.GetAttributeValue<string>("address1_postalcode");
			}
			set
			{
				this.SetAttributeValue("address1_postalcode", value);
			}
		}
		
		/// <summary>
		/// Número da caixa postal do endereço 1.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address1_postofficebox")]
		public string Address1_PostOfficeBox
		{
			get
			{
				return this.GetAttributeValue<string>("address1_postofficebox");
			}
			set
			{
				this.SetAttributeValue("address1_postofficebox", value);
			}
		}
		
		/// <summary>
		/// Método de entrega para endereço 1.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address1_shippingmethodcode")]
		public virtual systemuser_address1_shippingmethodcode? Address1_ShippingMethodCode
		{
			get
			{
				return ((systemuser_address1_shippingmethodcode?)(EntityOptionSetEnum.GetEnum(this, "address1_shippingmethodcode")));
			}
			set
			{
				this.SetAttributeValue("address1_shippingmethodcode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Estado do endereço 1.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address1_stateorprovince")]
		public string Address1_StateOrProvince
		{
			get
			{
				return this.GetAttributeValue<string>("address1_stateorprovince");
			}
			set
			{
				this.SetAttributeValue("address1_stateorprovince", value);
			}
		}
		
		/// <summary>
		/// Primeiro número de telefone associado ao endereço 1.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address1_telephone1")]
		public string Address1_Telephone1
		{
			get
			{
				return this.GetAttributeValue<string>("address1_telephone1");
			}
			set
			{
				this.SetAttributeValue("address1_telephone1", value);
			}
		}
		
		/// <summary>
		/// Segundo número de telefone associado ao endereço 1.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address1_telephone2")]
		public string Address1_Telephone2
		{
			get
			{
				return this.GetAttributeValue<string>("address1_telephone2");
			}
			set
			{
				this.SetAttributeValue("address1_telephone2", value);
			}
		}
		
		/// <summary>
		/// Terceiro número de telefone associado ao endereço 1.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address1_telephone3")]
		public string Address1_Telephone3
		{
			get
			{
				return this.GetAttributeValue<string>("address1_telephone3");
			}
			set
			{
				this.SetAttributeValue("address1_telephone3", value);
			}
		}
		
		/// <summary>
		/// Zona UPS do endereço 1.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address1_upszone")]
		public string Address1_UPSZone
		{
			get
			{
				return this.GetAttributeValue<string>("address1_upszone");
			}
			set
			{
				this.SetAttributeValue("address1_upszone", value);
			}
		}
		
		/// <summary>
		/// Diferença UTC do endereço 1. Essa é a diferença entre a hora local e a Hora Universal Coordenada oficial.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address1_utcoffset")]
		public System.Nullable<int> Address1_UTCOffset
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("address1_utcoffset");
			}
			set
			{
				this.SetAttributeValue("address1_utcoffset", value);
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do endereço 2.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address2_addressid")]
		public System.Nullable<System.Guid> Address2_AddressId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("address2_addressid");
			}
			set
			{
				this.SetAttributeValue("address2_addressid", value);
			}
		}
		
		/// <summary>
		/// Tipo do endereço 2, como por exemplo, endereço para cobrança, endereço para entrega ou endereço primário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address2_addresstypecode")]
		public virtual systemuser_address2_addresstypecode? Address2_AddressTypeCode
		{
			get
			{
				return ((systemuser_address2_addresstypecode?)(EntityOptionSetEnum.GetEnum(this, "address2_addresstypecode")));
			}
			set
			{
				this.SetAttributeValue("address2_addresstypecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Nome da cidade do endereço 2.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address2_city")]
		public string Address2_City
		{
			get
			{
				return this.GetAttributeValue<string>("address2_city");
			}
			set
			{
				this.SetAttributeValue("address2_city", value);
			}
		}
		
		/// <summary>
		/// Mostra o endereço secundário completo.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address2_composite")]
		public string Address2_Composite
		{
			get
			{
				return this.GetAttributeValue<string>("address2_composite");
			}
		}
		
		/// <summary>
		/// Nome do país/região em endereço 2.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address2_country")]
		public string Address2_Country
		{
			get
			{
				return this.GetAttributeValue<string>("address2_country");
			}
			set
			{
				this.SetAttributeValue("address2_country", value);
			}
		}
		
		/// <summary>
		/// Nome do município do endereço 2.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address2_county")]
		public string Address2_County
		{
			get
			{
				return this.GetAttributeValue<string>("address2_county");
			}
			set
			{
				this.SetAttributeValue("address2_county", value);
			}
		}
		
		/// <summary>
		/// Número de fax do endereço 2.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address2_fax")]
		public string Address2_Fax
		{
			get
			{
				return this.GetAttributeValue<string>("address2_fax");
			}
			set
			{
				this.SetAttributeValue("address2_fax", value);
			}
		}
		
		/// <summary>
		/// Latitude do endereço 2.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address2_latitude")]
		public System.Nullable<double> Address2_Latitude
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("address2_latitude");
			}
			set
			{
				this.SetAttributeValue("address2_latitude", value);
			}
		}
		
		/// <summary>
		/// Primeira linha para inserir informações de endereço 2.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address2_line1")]
		public string Address2_Line1
		{
			get
			{
				return this.GetAttributeValue<string>("address2_line1");
			}
			set
			{
				this.SetAttributeValue("address2_line1", value);
			}
		}
		
		/// <summary>
		/// Segunda linha para inserir informações de endereço 2.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address2_line2")]
		public string Address2_Line2
		{
			get
			{
				return this.GetAttributeValue<string>("address2_line2");
			}
			set
			{
				this.SetAttributeValue("address2_line2", value);
			}
		}
		
		/// <summary>
		/// Terceira linha para inserir informações de endereço 2.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address2_line3")]
		public string Address2_Line3
		{
			get
			{
				return this.GetAttributeValue<string>("address2_line3");
			}
			set
			{
				this.SetAttributeValue("address2_line3", value);
			}
		}
		
		/// <summary>
		/// Longitude do endereço 2.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address2_longitude")]
		public System.Nullable<double> Address2_Longitude
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("address2_longitude");
			}
			set
			{
				this.SetAttributeValue("address2_longitude", value);
			}
		}
		
		/// <summary>
		/// Nome a ser inserido para endereço 2.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address2_name")]
		public string Address2_Name
		{
			get
			{
				return this.GetAttributeValue<string>("address2_name");
			}
			set
			{
				this.SetAttributeValue("address2_name", value);
			}
		}
		
		/// <summary>
		/// CEP do endereço 2.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address2_postalcode")]
		public string Address2_PostalCode
		{
			get
			{
				return this.GetAttributeValue<string>("address2_postalcode");
			}
			set
			{
				this.SetAttributeValue("address2_postalcode", value);
			}
		}
		
		/// <summary>
		/// Número da caixa postal do endereço 2.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address2_postofficebox")]
		public string Address2_PostOfficeBox
		{
			get
			{
				return this.GetAttributeValue<string>("address2_postofficebox");
			}
			set
			{
				this.SetAttributeValue("address2_postofficebox", value);
			}
		}
		
		/// <summary>
		/// Método de entrega para endereço 2.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address2_shippingmethodcode")]
		public virtual systemuser_address2_shippingmethodcode? Address2_ShippingMethodCode
		{
			get
			{
				return ((systemuser_address2_shippingmethodcode?)(EntityOptionSetEnum.GetEnum(this, "address2_shippingmethodcode")));
			}
			set
			{
				this.SetAttributeValue("address2_shippingmethodcode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Estado do endereço 2.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address2_stateorprovince")]
		public string Address2_StateOrProvince
		{
			get
			{
				return this.GetAttributeValue<string>("address2_stateorprovince");
			}
			set
			{
				this.SetAttributeValue("address2_stateorprovince", value);
			}
		}
		
		/// <summary>
		/// Primeiro número de telefone associado ao endereço 2.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address2_telephone1")]
		public string Address2_Telephone1
		{
			get
			{
				return this.GetAttributeValue<string>("address2_telephone1");
			}
			set
			{
				this.SetAttributeValue("address2_telephone1", value);
			}
		}
		
		/// <summary>
		/// Segundo número de telefone associado ao endereço 2.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address2_telephone2")]
		public string Address2_Telephone2
		{
			get
			{
				return this.GetAttributeValue<string>("address2_telephone2");
			}
			set
			{
				this.SetAttributeValue("address2_telephone2", value);
			}
		}
		
		/// <summary>
		/// Terceiro número de telefone associado ao endereço 2.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address2_telephone3")]
		public string Address2_Telephone3
		{
			get
			{
				return this.GetAttributeValue<string>("address2_telephone3");
			}
			set
			{
				this.SetAttributeValue("address2_telephone3", value);
			}
		}
		
		/// <summary>
		/// Zona UPS do endereço 2.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address2_upszone")]
		public string Address2_UPSZone
		{
			get
			{
				return this.GetAttributeValue<string>("address2_upszone");
			}
			set
			{
				this.SetAttributeValue("address2_upszone", value);
			}
		}
		
		/// <summary>
		/// Diferença UTC do endereço 2. Essa é a diferença entre a hora local e a Hora Universal Coordenada oficial.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("address2_utcoffset")]
		public System.Nullable<int> Address2_UTCOffset
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("address2_utcoffset");
			}
			set
			{
				this.SetAttributeValue("address2_utcoffset", value);
			}
		}
		
		/// <summary>
		/// O identificador do aplicativo. É usado para acessar dados em outro aplicativo.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("applicationid")]
		public System.Nullable<System.Guid> ApplicationId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("applicationid");
			}
			set
			{
				this.SetAttributeValue("applicationid", value);
			}
		}
		
		/// <summary>
		/// O URI usado como identificador lógico exclusivo do aplicativo externo. Pode ser usado para validar o aplicativo.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("applicationiduri")]
		public string ApplicationIdUri
		{
			get
			{
				return this.GetAttributeValue<string>("applicationiduri");
			}
		}
		
		/// <summary>
		/// É a ID do objeto do diretório de aplicativos.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("azureactivedirectoryobjectid")]
		public System.Nullable<System.Guid> AzureActiveDirectoryObjectId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("azureactivedirectoryobjectid");
			}
		}
		
		/// <summary>
		/// Data e hora de quando o usuário estava definido como excluído temporariamente no Azure.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("azuredeletedon")]
		public System.Nullable<System.DateTime> AzureDeletedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("azuredeletedon");
			}
		}
		
		/// <summary>
		/// Estado do usuário do Azure
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("azurestate")]
		public virtual systemuser_azurestate? AzureState
		{
			get
			{
				return ((systemuser_azurestate?)(EntityOptionSetEnum.GetEnum(this, "azurestate")));
			}
			set
			{
				this.SetAttributeValue("azurestate", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Identificador exclusivo da unidade de negócios à qual o usuário está associado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("businessunitid")]
		public Microsoft.Xrm.Sdk.EntityReference BusinessUnitId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("businessunitid");
			}
			set
			{
				this.SetAttributeValue("businessunitid", value);
			}
		}
		
		/// <summary>
		/// Calendário fiscal associado ao usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("calendarid")]
		public Microsoft.Xrm.Sdk.EntityReference CalendarId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("calendarid");
			}
			set
			{
				this.SetAttributeValue("calendarid", value);
			}
		}
		
		/// <summary>
		/// Tipo de licença do usuário. Isso é usado somente na versão local do produto. As licenças online são gerenciadas por meio do Portal do Microsoft 365 Office
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("caltype")]
		public virtual systemuser_caltype? CALType
		{
			get
			{
				return ((systemuser_caltype?)(EntityOptionSetEnum.GetEnum(this, "caltype")));
			}
			set
			{
				this.SetAttributeValue("caltype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário que criou o  usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Data e hora em que o usuário foi criado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário delegado que criou o systemuser.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Indica se os filtros padrão do Outlook foram populados.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultfilterspopulated")]
		public System.Nullable<bool> DefaultFiltersPopulated
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("defaultfilterspopulated");
			}
		}
		
		/// <summary>
		/// Escolha a caixa de correio associada a este usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultmailbox")]
		public Microsoft.Xrm.Sdk.EntityReference DefaultMailbox
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defaultmailbox");
			}
		}
		
		/// <summary>
		/// Digite um nome de pasta padrão para o local do OneDrive For Business do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultodbfoldername")]
		public string DefaultOdbFolderName
		{
			get
			{
				return this.GetAttributeValue<string>("defaultodbfoldername");
			}
		}
		
		/// <summary>
		/// Estado de exclusão do usuário
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("deletedstate")]
		public virtual systemuser_deletestate? DeletedState
		{
			get
			{
				return ((systemuser_deletestate?)(EntityOptionSetEnum.GetEnum(this, "deletedstate")));
			}
		}
		
		/// <summary>
		/// Razão para desabilitar o usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("disabledreason")]
		public string DisabledReason
		{
			get
			{
				return this.GetAttributeValue<string>("disabledreason");
			}
		}
		
		/// <summary>
		/// Indicação se o usuário deve ser mostrado em exibições de serviço.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("displayinserviceviews")]
		public System.Nullable<bool> DisplayInServiceViews
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("displayinserviceviews");
			}
			set
			{
				this.SetAttributeValue("displayinserviceviews", value);
			}
		}
		
		/// <summary>
		/// Domínio do Active Directory do qual o usuário é membro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("domainname")]
		public string DomainName
		{
			get
			{
				return this.GetAttributeValue<string>("domainname");
			}
			set
			{
				this.SetAttributeValue("domainname", value);
			}
		}
		
		/// <summary>
		/// Mostra o status do endereço de email principal.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailrouteraccessapproval")]
		public virtual systemuser_emailrouteraccessapproval? EmailRouterAccessApproval
		{
			get
			{
				return ((systemuser_emailrouteraccessapproval?)(EntityOptionSetEnum.GetEnum(this, "emailrouteraccessapproval")));
			}
			set
			{
				this.SetAttributeValue("emailrouteraccessapproval", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Identificador de funcionário para o usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("employeeid")]
		public string EmployeeId
		{
			get
			{
				return this.GetAttributeValue<string>("employeeid");
			}
			set
			{
				this.SetAttributeValue("employeeid", value);
			}
		}
		
		/// <summary>
		/// Mostra a imagem padrão do registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage")]
		public byte[] EntityImage
		{
			get
			{
				return this.GetAttributeValue<byte[]>("entityimage");
			}
			set
			{
				this.SetAttributeValue("entityimage", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_timestamp")]
		public System.Nullable<long> EntityImage_Timestamp
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("entityimage_timestamp");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_url")]
		public string EntityImage_URL
		{
			get
			{
				return this.GetAttributeValue<string>("entityimage_url");
			}
		}
		
		/// <summary>
		/// Somente para uso interno.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimageid")]
		public System.Nullable<System.Guid> EntityImageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("entityimageid");
			}
		}
		
		/// <summary>
		/// Taxa de câmbio da moeda associada ao systemuser com relação à moeda base.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Nome do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("firstname")]
		public string FirstName
		{
			get
			{
				return this.GetAttributeValue<string>("firstname");
			}
			set
			{
				this.SetAttributeValue("firstname", value);
			}
		}
		
		/// <summary>
		/// Nome completo do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("fullname")]
		public string FullName
		{
			get
			{
				return this.GetAttributeValue<string>("fullname");
			}
		}
		
		/// <summary>
		/// Identificador de governo para o usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("governmentid")]
		public string GovernmentId
		{
			get
			{
				return this.GetAttributeValue<string>("governmentid");
			}
			set
			{
				this.SetAttributeValue("governmentid", value);
			}
		}
		
		/// <summary>
		/// Número do telefone residencial do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("homephone")]
		public string HomePhone
		{
			get
			{
				return this.GetAttributeValue<string>("homephone");
			}
			set
			{
				this.SetAttributeValue("homephone", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("i4d_email_contato")]
		public string i4d_email_contato
		{
			get
			{
				return this.GetAttributeValue<string>("i4d_email_contato");
			}
			set
			{
				this.SetAttributeValue("i4d_email_contato", value);
			}
		}
		
		/// <summary>
		/// Cargo em inglês para ser usado no report de oportunidade.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("i4d_positionheld")]
		public string i4d_positionheld
		{
			get
			{
				return this.GetAttributeValue<string>("i4d_positionheld");
			}
			set
			{
				this.SetAttributeValue("i4d_positionheld", value);
			}
		}
		
		/// <summary>
		/// Somente para uso interno.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("identityid")]
		public System.Nullable<int> IdentityId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("identityid");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo da importação de dados ou migração de dados que criou este registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Método de entrega de emails de entrada do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("incomingemaildeliverymethod")]
		public virtual systemuser_incomingemaildeliverymethod? IncomingEmailDeliveryMethod
		{
			get
			{
				return ((systemuser_incomingemaildeliverymethod?)(EntityOptionSetEnum.GetEnum(this, "incomingemaildeliverymethod")));
			}
			set
			{
				this.SetAttributeValue("incomingemaildeliverymethod", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Endereço de email interno do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("internalemailaddress")]
		public string InternalEMailAddress
		{
			get
			{
				return this.GetAttributeValue<string>("internalemailaddress");
			}
			set
			{
				this.SetAttributeValue("internalemailaddress", value);
			}
		}
		
		/// <summary>
		/// Status do convite do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("invitestatuscode")]
		public virtual systemuser_invitestatuscode? InviteStatusCode
		{
			get
			{
				return ((systemuser_invitestatuscode?)(EntityOptionSetEnum.GetEnum(this, "invitestatuscode")));
			}
			set
			{
				this.SetAttributeValue("invitestatuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Bypasses the selected user from IP firewall restriction
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isallowedbyipfirewall")]
		public System.Nullable<bool> IsAllowedByIpFirewall
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isallowedbyipfirewall");
			}
			set
			{
				this.SetAttributeValue("isallowedbyipfirewall", value);
			}
		}
		
		/// <summary>
		/// Especifica se  usuário está habilitado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isdisabled")]
		public System.Nullable<bool> IsDisabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isdisabled");
			}
			set
			{
				this.SetAttributeValue("isdisabled", value);
			}
		}
		
		/// <summary>
		/// Mostra o status da aprovação do endereço de email pelo administrador do O365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isemailaddressapprovedbyo365admin")]
		public System.Nullable<bool> IsEmailAddressApprovedByO365Admin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isemailaddressapprovedbyo365admin");
			}
		}
		
		/// <summary>
		/// Verifique se o usuário é um usuário de integração.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isintegrationuser")]
		public System.Nullable<bool> IsIntegrationUser
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isintegrationuser");
			}
			set
			{
				this.SetAttributeValue("isintegrationuser", value);
			}
		}
		
		/// <summary>
		/// Informações se o usuário é licenciado ou não.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("islicensed")]
		public System.Nullable<bool> IsLicensed
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("islicensed");
			}
			set
			{
				this.SetAttributeValue("islicensed", value);
			}
		}
		
		/// <summary>
		/// Informação que especifica se o usuário está sincronizado ou não com o diretório.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("issyncwithdirectory")]
		public System.Nullable<bool> IsSyncWithDirectory
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("issyncwithdirectory");
			}
			set
			{
				this.SetAttributeValue("issyncwithdirectory", value);
			}
		}
		
		/// <summary>
		/// Cargo do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("jobtitle")]
		public string JobTitle
		{
			get
			{
				return this.GetAttributeValue<string>("jobtitle");
			}
			set
			{
				this.SetAttributeValue("jobtitle", value);
			}
		}
		
		/// <summary>
		/// Sobrenome do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lastname")]
		public string LastName
		{
			get
			{
				return this.GetAttributeValue<string>("lastname");
			}
			set
			{
				this.SetAttributeValue("lastname", value);
			}
		}
		
		/// <summary>
		/// Segundo nome do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("middlename")]
		public string MiddleName
		{
			get
			{
				return this.GetAttributeValue<string>("middlename");
			}
			set
			{
				this.SetAttributeValue("middlename", value);
			}
		}
		
		/// <summary>
		/// Endereço de email de alerta do celular do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mobilealertemail")]
		public string MobileAlertEMail
		{
			get
			{
				return this.GetAttributeValue<string>("mobilealertemail");
			}
			set
			{
				this.SetAttributeValue("mobilealertemail", value);
			}
		}
		
		/// <summary>
		/// Itens contidos em um SystemUser específico.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mobileofflineprofileid")]
		public Microsoft.Xrm.Sdk.EntityReference MobileOfflineProfileId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("mobileofflineprofileid");
			}
			set
			{
				this.SetAttributeValue("mobileofflineprofileid", value);
			}
		}
		
		/// <summary>
		/// Número do celular do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mobilephone")]
		public string MobilePhone
		{
			get
			{
				return this.GetAttributeValue<string>("mobilephone");
			}
			set
			{
				this.SetAttributeValue("mobilephone", value);
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário que modificou o usuário por último.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Data e hora da última modificação do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário delegado que modificou o systemuser pela última vez.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Tipo de usuário – Usuário de aplicativo ou de aplicativo de bot
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_agentType")]
		public virtual msdyn_systemuser_msdyn_agentType? msdyn_AgentType
		{
			get
			{
				return ((msdyn_systemuser_msdyn_agentType?)(EntityOptionSetEnum.GetEnum(this, "msdyn_agentType")));
			}
			set
			{
				this.SetAttributeValue("msdyn_agentType", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// ID do Aplicativo de bot.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_botapplicationid")]
		public string msdyn_BotApplicationId
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_botapplicationid");
			}
			set
			{
				this.SetAttributeValue("msdyn_botapplicationid", value);
			}
		}
		
		/// <summary>
		/// Descrição do Usuário de BOT
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_botdescription")]
		public string msdyn_BotDescription
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_botdescription");
			}
			set
			{
				this.SetAttributeValue("msdyn_botdescription", value);
			}
		}
		
		/// <summary>
		/// Ponto de Extremidade do Usuário de Bot
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_botendpoint")]
		public string msdyn_BotEndpoint
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_botendpoint");
			}
			set
			{
				this.SetAttributeValue("msdyn_botendpoint", value);
			}
		}
		
		/// <summary>
		/// Identificador do bot
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_bothandle")]
		public string msdyn_bothandle
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_bothandle");
			}
			set
			{
				this.SetAttributeValue("msdyn_bothandle", value);
			}
		}
		
		/// <summary>
		/// Indica o tipo de bot
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_botprovider")]
		public virtual msdyn_systemuser_msdyn_botprovider? msdyn_BotProvider
		{
			get
			{
				return ((msdyn_systemuser_msdyn_botprovider?)(EntityOptionSetEnum.GetEnum(this, "msdyn_botprovider")));
			}
			set
			{
				this.SetAttributeValue("msdyn_botprovider", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Chaves Secretas do Usuário de Bot
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_botsecretkeys")]
		public string msdyn_BotSecretKeys
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_botsecretkeys");
			}
			set
			{
				this.SetAttributeValue("msdyn_botsecretkeys", value);
			}
		}
		
		/// <summary>
		/// Capacidade associada ao Usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_capacity")]
		public System.Nullable<int> msdyn_Capacity
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msdyn_capacity");
			}
			set
			{
				this.SetAttributeValue("msdyn_capacity", value);
			}
		}
		
		/// <summary>
		/// Identificador exclusivo da Presença associada ao Usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_defaultpresenceiduser")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_DefaultPresenceIdUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_defaultpresenceiduser");
			}
			set
			{
				this.SetAttributeValue("msdyn_defaultpresenceiduser", value);
			}
		}
		
		/// <summary>
		/// Descreve se o usuário foi recusado ou não
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_gdproptout")]
		public System.Nullable<bool> msdyn_gdproptout
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_gdproptout");
			}
			set
			{
				this.SetAttributeValue("msdyn_gdproptout", value);
			}
		}
		
		/// <summary>
		/// Campo para vincular o controle de wrapper de grade
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_gridwrappercontrolfield")]
		public string msdyn_gridwrappercontrolfield
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_gridwrappercontrolfield");
			}
			set
			{
				this.SetAttributeValue("msdyn_gridwrappercontrolfield", value);
			}
		}
		
		/// <summary>
		/// Verifique se a associação está habilitada para os especialistas.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_isexpertenabledforswarm")]
		public System.Nullable<bool> msdyn_isexpertenabledforswarm
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_isexpertenabledforswarm");
			}
			set
			{
				this.SetAttributeValue("msdyn_isexpertenabledforswarm", value);
			}
		}
		
		/// <summary>
		/// ID do ambiente CDS que é proprietário do usuário do bot.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_owningenvironmentid")]
		public string msdyn_OwningEnvironmentId
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_owningenvironmentid");
			}
			set
			{
				this.SetAttributeValue("msdyn_owningenvironmentid", value);
			}
		}
		
		/// <summary>
		/// Tipo de usuário - usuário do CRM ou BOT
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_usertype")]
		public virtual msdyn_systemuser_msdyn_usertype? msdyn_UserType
		{
			get
			{
				return ((msdyn_systemuser_msdyn_usertype?)(EntityOptionSetEnum.GetEnum(this, "msdyn_usertype")));
			}
			set
			{
				this.SetAttributeValue("msdyn_usertype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Apelido do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nickname")]
		public string NickName
		{
			get
			{
				return this.GetAttributeValue<string>("nickname");
			}
			set
			{
				this.SetAttributeValue("nickname", value);
			}
		}
		
		/// <summary>
		/// Identificador exclusivo da organização associada ao usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public System.Nullable<System.Guid> OrganizationId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("organizationid");
			}
		}
		
		/// <summary>
		/// Método de entrega de emails de saída do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("outgoingemaildeliverymethod")]
		public virtual systemuser_outgoingemaildeliverymethod? OutgoingEmailDeliveryMethod
		{
			get
			{
				return ((systemuser_outgoingemaildeliverymethod?)(EntityOptionSetEnum.GetEnum(this, "outgoingemaildeliverymethod")));
			}
			set
			{
				this.SetAttributeValue("outgoingemaildeliverymethod", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Data e hora da migração do registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do gerente do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentsystemuserid")]
		public Microsoft.Xrm.Sdk.EntityReference ParentSystemUserId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("parentsystemuserid");
			}
			set
			{
				this.SetAttributeValue("parentsystemuserid", value);
			}
		}
		
		/// <summary>
		/// Apenas para uso interno.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("passporthi")]
		public System.Nullable<int> PassportHi
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("passporthi");
			}
			set
			{
				this.SetAttributeValue("passporthi", value);
			}
		}
		
		/// <summary>
		/// Apenas para uso interno.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("passportlo")]
		public System.Nullable<int> PassportLo
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("passportlo");
			}
			set
			{
				this.SetAttributeValue("passportlo", value);
			}
		}
		
		/// <summary>
		/// Endereço de email pessoal do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("personalemailaddress")]
		public string PersonalEMailAddress
		{
			get
			{
				return this.GetAttributeValue<string>("personalemailaddress");
			}
			set
			{
				this.SetAttributeValue("personalemailaddress", value);
			}
		}
		
		/// <summary>
		/// URL do site em que a foto do usuário está localizada.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("photourl")]
		public string PhotoUrl
		{
			get
			{
				return this.GetAttributeValue<string>("photourl");
			}
			set
			{
				this.SetAttributeValue("photourl", value);
			}
		}
		
		/// <summary>
		/// Posição do usuário no modelo de segurança hierárquica.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("positionid")]
		public Microsoft.Xrm.Sdk.EntityReference PositionId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("positionid");
			}
			set
			{
				this.SetAttributeValue("positionid", value);
			}
		}
		
		/// <summary>
		/// Endereço preferencial do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("preferredaddresscode")]
		public virtual systemuser_preferredaddresscode? PreferredAddressCode
		{
			get
			{
				return ((systemuser_preferredaddresscode?)(EntityOptionSetEnum.GetEnum(this, "preferredaddresscode")));
			}
			set
			{
				this.SetAttributeValue("preferredaddresscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Endereço de email preferencial do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("preferredemailcode")]
		public virtual systemuser_preferredemailcode? PreferredEmailCode
		{
			get
			{
				return ((systemuser_preferredemailcode?)(EntityOptionSetEnum.GetEnum(this, "preferredemailcode")));
			}
			set
			{
				this.SetAttributeValue("preferredemailcode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Número de telefone preferencial do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("preferredphonecode")]
		public virtual systemuser_preferredphonecode? PreferredPhoneCode
		{
			get
			{
				return ((systemuser_preferredphonecode?)(EntityOptionSetEnum.GetEnum(this, "preferredphonecode")));
			}
			set
			{
				this.SetAttributeValue("preferredphonecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Mostra a ID do processo.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
		public System.Nullable<System.Guid> ProcessId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
			}
			set
			{
				this.SetAttributeValue("processid", value);
			}
		}
		
		/// <summary>
		/// Identificador exclusivo da fila padrão do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("queueid")]
		public Microsoft.Xrm.Sdk.EntityReference QueueId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("queueid");
			}
			set
			{
				this.SetAttributeValue("queueid", value);
			}
		}
		
		/// <summary>
		/// Saudação para correspondências com o usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("salutation")]
		public string Salutation
		{
			get
			{
				return this.GetAttributeValue<string>("salutation");
			}
			set
			{
				this.SetAttributeValue("salutation", value);
			}
		}
		
		/// <summary>
		/// Verificar se o usuário é um usuário de instalação.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("setupuser")]
		public System.Nullable<bool> SetupUser
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("setupuser");
			}
			set
			{
				this.SetAttributeValue("setupuser", value);
			}
		}
		
		/// <summary>
		/// Endereço de Email de Trabalho do SharePoint
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sharepointemailaddress")]
		public string SharePointEmailAddress
		{
			get
			{
				return this.GetAttributeValue<string>("sharepointemailaddress");
			}
			set
			{
				this.SetAttributeValue("sharepointemailaddress", value);
			}
		}
		
		/// <summary>
		/// site_system_users
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("siteid")]
		public Microsoft.Xrm.Sdk.EntityReference SiteId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("siteid");
			}
			set
			{
				this.SetAttributeValue("siteid", value);
			}
		}
		
		/// <summary>
		/// Conjunto de qualificações do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("skills")]
		public string Skills
		{
			get
			{
				return this.GetAttributeValue<string>("skills");
			}
			set
			{
				this.SetAttributeValue("skills", value);
			}
		}
		
		/// <summary>
		/// Mostra a ID do estágio.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
		public System.Nullable<System.Guid> StageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
			}
			set
			{
				this.SetAttributeValue("stageid", value);
			}
		}
		
		/// <summary>
		/// O tipo de usuário
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("systemmanagedusertype")]
		public virtual systemuser_systemmanagedusertype? SystemManagedUserType
		{
			get
			{
				return ((systemuser_systemmanagedusertype?)(EntityOptionSetEnum.GetEnum(this, "systemmanagedusertype")));
			}
			set
			{
				this.SetAttributeValue("systemmanagedusertype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("systemuserid")]
		public System.Nullable<System.Guid> SystemUserId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("systemuserid");
			}
			set
			{
				this.SetAttributeValue("systemuserid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("systemuserid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.SystemUserId = value;
			}
		}
		
		/// <summary>
		/// territory_system_users
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("territoryid")]
		public Microsoft.Xrm.Sdk.EntityReference TerritoryId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("territoryid");
			}
			set
			{
				this.SetAttributeValue("territoryid", value);
			}
		}
		
		/// <summary>
		/// Apenas para uso interno.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Título do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("title")]
		public string Title
		{
			get
			{
				return this.GetAttributeValue<string>("title");
			}
			set
			{
				this.SetAttributeValue("title", value);
			}
		}
		
		/// <summary>
		/// Identificador exclusivo da moeda associada ao systemuser.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.SetAttributeValue("transactioncurrencyid", value);
			}
		}
		
		/// <summary>
		/// Apenas para uso interno.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("traversedpath")]
		public string TraversedPath
		{
			get
			{
				return this.GetAttributeValue<string>("traversedpath");
			}
			set
			{
				this.SetAttributeValue("traversedpath", value);
			}
		}
		
		/// <summary>
		/// Mostra o tipo de licença de usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("userlicensetype")]
		public System.Nullable<int> UserLicenseType
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("userlicensetype");
			}
			set
			{
				this.SetAttributeValue("userlicensetype", value);
			}
		}
		
		/// <summary>
		///  Informações Identificáveis do PUID do Usuário
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("userpuid")]
		public string UserPuid
		{
			get
			{
				return this.GetAttributeValue<string>("userpuid");
			}
		}
		
		/// <summary>
		/// Código de fuso horário em uso quando o registro foi criado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Número da versão do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// Windows Live ID
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("windowsliveid")]
		public string WindowsLiveID
		{
			get
			{
				return this.GetAttributeValue<string>("windowsliveid");
			}
			set
			{
				this.SetAttributeValue("windowsliveid", value);
			}
		}
		
		/// <summary>
		/// Endereço de email de logon no Yammer do usuário
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yammeremailaddress")]
		public string YammerEmailAddress
		{
			get
			{
				return this.GetAttributeValue<string>("yammeremailaddress");
			}
			set
			{
				this.SetAttributeValue("yammeremailaddress", value);
			}
		}
		
		/// <summary>
		/// ID do Usuário do Yammer
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yammeruserid")]
		public string YammerUserId
		{
			get
			{
				return this.GetAttributeValue<string>("yammeruserid");
			}
			set
			{
				this.SetAttributeValue("yammeruserid", value);
			}
		}
		
		/// <summary>
		/// Pronúncia do nome do usuário, escrito em caracteres fonéticos hiragana ou katakana.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yomifirstname")]
		public string YomiFirstName
		{
			get
			{
				return this.GetAttributeValue<string>("yomifirstname");
			}
			set
			{
				this.SetAttributeValue("yomifirstname", value);
			}
		}
		
		/// <summary>
		/// Pronúncia do nome completo do usuário, escrito em caracteres fonéticos hiragana ou katakana.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yomifullname")]
		public string YomiFullName
		{
			get
			{
				return this.GetAttributeValue<string>("yomifullname");
			}
		}
		
		/// <summary>
		/// Pronúncia do sobrenome do usuário, escrito em caracteres fonéticos hiragana ou katakana.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yomilastname")]
		public string YomiLastName
		{
			get
			{
				return this.GetAttributeValue<string>("yomilastname");
			}
			set
			{
				this.SetAttributeValue("yomilastname", value);
			}
		}
		
		/// <summary>
		/// Pronúncia do segundo nome do usuário, escrito em caracteres fonéticos hiragana ou katakana.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yomimiddlename")]
		public string YomiMiddleName
		{
			get
			{
				return this.GetAttributeValue<string>("yomimiddlename");
			}
			set
			{
				this.SetAttributeValue("yomimiddlename", value);
			}
		}
		
		/// <summary>
		/// 1:N lk_businessunit_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_businessunit_createdonbehalfby")]
		public System.Collections.Generic.IEnumerable<project_plugins.earlybound.BusinessUnit> lk_businessunit_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntities<project_plugins.earlybound.BusinessUnit>("lk_businessunit_createdonbehalfby", null);
			}
			set
			{
				this.SetRelatedEntities<project_plugins.earlybound.BusinessUnit>("lk_businessunit_createdonbehalfby", null, value);
			}
		}
		
		/// <summary>
		/// 1:N lk_businessunit_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_businessunit_modifiedonbehalfby")]
		public System.Collections.Generic.IEnumerable<project_plugins.earlybound.BusinessUnit> lk_businessunit_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntities<project_plugins.earlybound.BusinessUnit>("lk_businessunit_modifiedonbehalfby", null);
			}
			set
			{
				this.SetRelatedEntities<project_plugins.earlybound.BusinessUnit>("lk_businessunit_modifiedonbehalfby", null, value);
			}
		}
		
		/// <summary>
		/// 1:N lk_businessunitbase_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_businessunitbase_createdby")]
		public System.Collections.Generic.IEnumerable<project_plugins.earlybound.BusinessUnit> lk_businessunitbase_createdby
		{
			get
			{
				return this.GetRelatedEntities<project_plugins.earlybound.BusinessUnit>("lk_businessunitbase_createdby", null);
			}
			set
			{
				this.SetRelatedEntities<project_plugins.earlybound.BusinessUnit>("lk_businessunitbase_createdby", null, value);
			}
		}
		
		/// <summary>
		/// 1:N lk_businessunitbase_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_businessunitbase_modifiedby")]
		public System.Collections.Generic.IEnumerable<project_plugins.earlybound.BusinessUnit> lk_businessunitbase_modifiedby
		{
			get
			{
				return this.GetRelatedEntities<project_plugins.earlybound.BusinessUnit>("lk_businessunitbase_modifiedby", null);
			}
			set
			{
				this.SetRelatedEntities<project_plugins.earlybound.BusinessUnit>("lk_businessunitbase_modifiedby", null, value);
			}
		}

		/// <summary>
		/// 1:N lk_systemuser_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_systemuser_createdonbehalfby", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<project_plugins.earlybound.SystemUser> Referencedlk_systemuser_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntities<project_plugins.earlybound.SystemUser>("lk_systemuser_createdonbehalfby", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.SetRelatedEntities<project_plugins.earlybound.SystemUser>("lk_systemuser_createdonbehalfby", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			}
		}
		
		/// <summary>
		/// 1:N lk_systemuser_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_systemuser_modifiedonbehalfby", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<project_plugins.earlybound.SystemUser> Referencedlk_systemuser_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntities<project_plugins.earlybound.SystemUser>("lk_systemuser_modifiedonbehalfby", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.SetRelatedEntities<project_plugins.earlybound.SystemUser>("lk_systemuser_modifiedonbehalfby", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			}
		}
		
		/// <summary>
		/// 1:N lk_systemuserbase_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_systemuserbase_createdby", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<project_plugins.earlybound.SystemUser> Referencedlk_systemuserbase_createdby
		{
			get
			{
				return this.GetRelatedEntities<project_plugins.earlybound.SystemUser>("lk_systemuserbase_createdby", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.SetRelatedEntities<project_plugins.earlybound.SystemUser>("lk_systemuserbase_createdby", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			}
		}
		
		/// <summary>
		/// 1:N lk_systemuserbase_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_systemuserbase_modifiedby", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<project_plugins.earlybound.SystemUser> Referencedlk_systemuserbase_modifiedby
		{
			get
			{
				return this.GetRelatedEntities<project_plugins.earlybound.SystemUser>("lk_systemuserbase_modifiedby", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.SetRelatedEntities<project_plugins.earlybound.SystemUser>("lk_systemuserbase_modifiedby", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			}
		}
		
		/// <summary>
		/// 1:N lk_team_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_team_createdonbehalfby")]
		public System.Collections.Generic.IEnumerable<project_plugins.earlybound.Team> lk_team_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntities<project_plugins.earlybound.Team>("lk_team_createdonbehalfby", null);
			}
			set
			{
				this.SetRelatedEntities<project_plugins.earlybound.Team>("lk_team_createdonbehalfby", null, value);
			}
		}
		
		/// <summary>
		/// 1:N lk_team_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_team_modifiedonbehalfby")]
		public System.Collections.Generic.IEnumerable<project_plugins.earlybound.Team> lk_team_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntities<project_plugins.earlybound.Team>("lk_team_modifiedonbehalfby", null);
			}
			set
			{
				this.SetRelatedEntities<project_plugins.earlybound.Team>("lk_team_modifiedonbehalfby", null, value);
			}
		}
		
		/// <summary>
		/// 1:N lk_teambase_administratorid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_teambase_administratorid")]
		public System.Collections.Generic.IEnumerable<project_plugins.earlybound.Team> lk_teambase_administratorid
		{
			get
			{
				return this.GetRelatedEntities<project_plugins.earlybound.Team>("lk_teambase_administratorid", null);
			}
			set
			{
				this.SetRelatedEntities<project_plugins.earlybound.Team>("lk_teambase_administratorid", null, value);
			}
		}
		
		/// <summary>
		/// 1:N lk_teambase_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_teambase_createdby")]
		public System.Collections.Generic.IEnumerable<project_plugins.earlybound.Team> lk_teambase_createdby
		{
			get
			{
				return this.GetRelatedEntities<project_plugins.earlybound.Team>("lk_teambase_createdby", null);
			}
			set
			{
				this.SetRelatedEntities<project_plugins.earlybound.Team>("lk_teambase_createdby", null, value);
			}
		}
		
		/// <summary>
		/// 1:N lk_teambase_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_teambase_modifiedby")]
		public System.Collections.Generic.IEnumerable<project_plugins.earlybound.Team> lk_teambase_modifiedby
		{
			get
			{
				return this.GetRelatedEntities<project_plugins.earlybound.Team>("lk_teambase_modifiedby", null);
			}
			set
			{
				this.SetRelatedEntities<project_plugins.earlybound.Team>("lk_teambase_modifiedby", null, value);
			}
		}
		
		/// <summary>
		/// N:N teammembership_association
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("teammembership_association")]
		public System.Collections.Generic.IEnumerable<project_plugins.earlybound.Team> teammembership_association
		{
			get
			{
				return this.GetRelatedEntities<project_plugins.earlybound.Team>("teammembership_association", null);
			}
			set
			{
				this.SetRelatedEntities<project_plugins.earlybound.Team>("teammembership_association", null, value);
			}
		}
		
		/// <summary>
		/// N:1 business_unit_system_users
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("businessunitid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_system_users")]
		public project_plugins.earlybound.BusinessUnit business_unit_system_users
		{
			get
			{
				return this.GetRelatedEntity<project_plugins.earlybound.BusinessUnit>("business_unit_system_users", null);
			}
			set
			{
				this.SetRelatedEntity<project_plugins.earlybound.BusinessUnit>("business_unit_system_users", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_systemuser_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_systemuser_createdonbehalfby", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public project_plugins.earlybound.SystemUser Referencinglk_systemuser_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<project_plugins.earlybound.SystemUser>("lk_systemuser_createdonbehalfby", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
		}
		
		/// <summary>
		/// N:1 lk_systemuser_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_systemuser_modifiedonbehalfby", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public project_plugins.earlybound.SystemUser Referencinglk_systemuser_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<project_plugins.earlybound.SystemUser>("lk_systemuser_modifiedonbehalfby", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
		}
		
		/// <summary>
		/// N:1 lk_systemuserbase_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_systemuserbase_createdby", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public project_plugins.earlybound.SystemUser Referencinglk_systemuserbase_createdby
		{
			get
			{
				return this.GetRelatedEntity<project_plugins.earlybound.SystemUser>("lk_systemuserbase_createdby", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
		}
		
		/// <summary>
		/// N:1 lk_systemuserbase_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_systemuserbase_modifiedby", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public project_plugins.earlybound.SystemUser Referencinglk_systemuserbase_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<project_plugins.earlybound.SystemUser>("lk_systemuserbase_modifiedby", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
		}
		
		/// <summary>
		/// N:1 user_parent_user
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentsystemuserid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_parent_user", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public project_plugins.earlybound.SystemUser Referencinguser_parent_user
		{
			get
			{
				return this.GetRelatedEntity<project_plugins.earlybound.SystemUser>("user_parent_user", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			set
			{
				this.SetRelatedEntity<project_plugins.earlybound.SystemUser>("user_parent_user", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			}
		}
	}
}
#pragma warning restore CS1591
