#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_plugins.earlybound
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("teamroles")]
	public partial class TeamRoles : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the teamroles entity
		/// </summary>
		public partial class Fields
		{
			public const string RoleId = "roleid";
			public const string TeamId = "teamid";
			public const string TeamRoleId = "teamroleid";
			public const string Id = "teamroleid";
			public const string VersionNumber = "versionnumber";
			public const string teamroles_association = "teamroles_association";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public TeamRoles() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "teamroles";
		
		public const string EntityLogicalCollectionName = null;
		
		public const string EntitySetName = "teamrolescollection";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("roleid")]
		public System.Nullable<System.Guid> RoleId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("roleid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("teamid")]
		public System.Nullable<System.Guid> TeamId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("teamid");
			}
		}
		
		/// <summary>
		/// Apenas para uso interno.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("teamroleid")]
		public System.Nullable<System.Guid> TeamRoleId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("teamroleid");
			}
			set
			{
				this.SetAttributeValue("teamroleid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("teamroleid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.TeamRoleId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:N teamroles_association
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("teamroles_association")]
		public System.Collections.Generic.IEnumerable<project_plugins.earlybound.Team> teamroles_association
		{
			get
			{
				return this.GetRelatedEntities<project_plugins.earlybound.Team>("teamroles_association", null);
			}
			set
			{
				this.SetRelatedEntities<project_plugins.earlybound.Team>("teamroles_association", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
