#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_plugins.earlybound
{
	
	
	/// <summary>
	/// Determina se o status da tentativa de instalação automática do Dynamics 365 para Teams foi concluída
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum usersettings_d365autoinstallattemptstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Notentada = 0,
		
		/// <summary>
		/// Dynamics 365 App installed successfully
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Instaladoautomaticamente = 1,
		
		/// <summary>
		/// Dynamics 365 app is already installed in Teams
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Jinstalado = 2,
		
		/// <summary>
		/// Teams admin blocked installing Dynamics 365 app
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BloqueadopeloadministradordoTeams = 3,
		
		/// <summary>
		/// Not authorized to execute auto install
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Noautorizado = 4,
		
		/// <summary>
		/// D365 auto install solution is no available
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NenhumaSoluo = 5,
		
		/// <summary>
		/// Graph API is not available for auto install
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NenhumaAPIdoGraph = 6,
		
		/// <summary>
		/// Resource to call graph api is disabled by tenant
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RecursoDesabilitado = 7,
	}
	
	/// <summary>
	/// Informação que especifica o nível de validação de dados em planilhas do Excel exportada em um formato adequado para importação.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum usersettings_datavalidationmodeforexporttoexcel
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Completo = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Nenhum = 1,
	}
	
	/// <summary>
	/// Experiência de pesquisa padrão para o usuário.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum usersettings_defaultsearchexperience
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Usarltimapesquisa = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pesquisaderelevncia = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pesquisacategorizada = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pesquisapersonalizada = 3,
	}
	
	/// <summary>
	/// Informações que especificam o modo de formulário preferencial.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum usersettings_entityformmode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Padrodaorganizao = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Otimizadoparaleitura = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Editar = 2,
	}
	
	/// <summary>
	/// Método de filtragem de emails de entrada.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum usersettings_incomingemailfilteringmethod
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Todasasmensagensdeemail = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MensagensdeemailemrespostaaoemaildoDynamics365 = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MensagensdeemaildeClientesPotenciaisContatoseContasdoDynamics365 = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MensagensdeemailderegistrosdoDynamics365habilitadosparaemail = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Nenhumamensagemdeemail = 4,
	}
	
	/// <summary>
	/// Substituição de canal do aplicativo de modelo
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum usersettings_releasechannel
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Nenhum = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Substituiodecanalsemestral = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Substituiodecanalmensal = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Substituiodecanalinterno = 3,
	}
	
	/// <summary>
	/// Lista de opções para selecionar a preferência do usuário ao informar erros de script.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum usersettings_reportscripterrors
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PedirminhapermissoparaenviarumrelatriodeerroMicrosoft = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EnviarautomaticamenteumrelatriodeerroMicrosoftsempedirminhapermisso = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NuncaenviarumrelatriodeerrodoMicrosoftDynamics365Microsoft = 3,
	}
	
	/// <summary>
	/// O layout do painel de visualização.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum usersettings_visualizationpanelayout
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeCimaparaBaixo = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Ladoalado = 1,
	}
	
	/// <summary>
	/// Configurações preferenciais do usuário.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("usersettings")]
	public partial class UserSettings : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the usersettings entity
		/// </summary>
		public partial class Fields
		{
			public const string AddressBookSyncInterval = "addressbooksyncinterval";
			public const string AdvancedFindStartupMode = "advancedfindstartupmode";
			public const string AllowEmailCredentials = "allowemailcredentials";
			public const string AMDesignator = "amdesignator";
			public const string AutoCaptureUserStatus = "autocaptureuserstatus";
			public const string AutoCreateContactOnPromote = "autocreatecontactonpromote";
			public const string BusinessUnitId = "businessunitid";
			public const string CalendarType = "calendartype";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CurrencyDecimalPrecision = "currencydecimalprecision";
			public const string CurrencyFormatCode = "currencyformatcode";
			public const string CurrencySymbol = "currencysymbol";
			public const string D365AutoInstallAttemptStatus = "d365autoinstallattemptstatus";
			public const string DataValidationModeForExportToExcel = "datavalidationmodeforexporttoexcel";
			public const string DateFormatCode = "dateformatcode";
			public const string DateFormatString = "dateformatstring";
			public const string DateSeparator = "dateseparator";
			public const string DecimalSymbol = "decimalsymbol";
			public const string DefaultCalendarView = "defaultcalendarview";
			public const string DefaultCountryCode = "defaultcountrycode";
			public const string DefaultDashboardId = "defaultdashboardid";
			public const string DefaultSearchExperience = "defaultsearchexperience";
			public const string EmailPassword = "emailpassword";
			public const string EmailUsername = "emailusername";
			public const string EntityFormMode = "entityformmode";
			public const string FullNameConventionCode = "fullnameconventioncode";
			public const string GetStartedPaneContentEnabled = "getstartedpanecontentenabled";
			public const string HelpLanguageId = "helplanguageid";
			public const string HomepageArea = "homepagearea";
			public const string HomepageLayout = "homepagelayout";
			public const string HomepageSubarea = "homepagesubarea";
			public const string IgnoreUnsolicitedEmail = "ignoreunsolicitedemail";
			public const string IncomingEmailFilteringMethod = "incomingemailfilteringmethod";
			public const string IsAppsForCrmAlertDismissed = "isappsforcrmalertdismissed";
			public const string IsAutoDataCaptureEnabled = "isautodatacaptureenabled";
			public const string IsDefaultCountryCodeCheckEnabled = "isdefaultcountrycodecheckenabled";
			public const string IsDuplicateDetectionEnabledWhenGoingOnline = "isduplicatedetectionenabledwhengoingonline";
			public const string IsEmailConversationViewEnabled = "isemailconversationviewenabled";
			public const string IsGuidedHelpEnabled = "isguidedhelpenabled";
			public const string IsResourceBookingExchangeSyncEnabled = "isresourcebookingexchangesyncenabled";
			public const string IsSendAsAllowed = "issendasallowed";
			public const string LastAlertsViewedTime = "lastalertsviewedtime";
			public const string LastModifiedTimeForViewPersonalizationSettings = "lastmodifiedtimeforviewpersonalizationsettings";
			public const string LocaleId = "localeid";
			public const string LongDateFormatCode = "longdateformatcode";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string NegativeCurrencyFormatCode = "negativecurrencyformatcode";
			public const string NegativeFormatCode = "negativeformatcode";
			public const string NextTrackingNumber = "nexttrackingnumber";
			public const string NumberGroupFormat = "numbergroupformat";
			public const string NumberSeparator = "numberseparator";
			public const string OfflineSyncInterval = "offlinesyncinterval";
			public const string OutlookSyncInterval = "outlooksyncinterval";
			public const string PagingLimit = "paginglimit";
			public const string PersonalizationSettings = "personalizationsettings";
			public const string PMDesignator = "pmdesignator";
			public const string PreferredSolution = "preferredsolution";
			public const string PricingDecimalPrecision = "pricingdecimalprecision";
			public const string ReleaseChannel = "releasechannel";
			public const string ReportScriptErrors = "reportscripterrors";
			public const string ResourceBookingExchangeSyncVersion = "resourcebookingexchangesyncversion";
			public const string SelectedGlobalFilterId = "selectedglobalfilterid";
			public const string ShowWeekNumber = "showweeknumber";
			public const string SplitViewState = "splitviewstate";
			public const string SyncContactCompany = "synccontactcompany";
			public const string SystemUserId = "systemuserid";
			public const string Id = "systemuserid";
			public const string TableScopedDVSearchFeatureTeachingBubbleViews = "tablescopeddvsearchfeatureteachingbubbleviews";
			public const string TableScopedDVSearchQuickFindTeachingBubbleViews = "tablescopeddvsearchquickfindteachingbubbleviews";
			public const string TimeFormatCode = "timeformatcode";
			public const string TimeFormatString = "timeformatstring";
			public const string TimeSeparator = "timeseparator";
			public const string TimeZoneBias = "timezonebias";
			public const string TimeZoneCode = "timezonecode";
			public const string TimeZoneDaylightBias = "timezonedaylightbias";
			public const string TimeZoneDaylightDay = "timezonedaylightday";
			public const string TimeZoneDaylightDayOfWeek = "timezonedaylightdayofweek";
			public const string TimeZoneDaylightHour = "timezonedaylighthour";
			public const string TimeZoneDaylightMinute = "timezonedaylightminute";
			public const string TimeZoneDaylightMonth = "timezonedaylightmonth";
			public const string TimeZoneDaylightSecond = "timezonedaylightsecond";
			public const string TimeZoneDaylightYear = "timezonedaylightyear";
			public const string TimeZoneStandardBias = "timezonestandardbias";
			public const string TimeZoneStandardDay = "timezonestandardday";
			public const string TimeZoneStandardDayOfWeek = "timezonestandarddayofweek";
			public const string TimeZoneStandardHour = "timezonestandardhour";
			public const string TimeZoneStandardMinute = "timezonestandardminute";
			public const string TimeZoneStandardMonth = "timezonestandardmonth";
			public const string TimeZoneStandardSecond = "timezonestandardsecond";
			public const string TimeZoneStandardYear = "timezonestandardyear";
			public const string TrackingTokenId = "trackingtokenid";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string TryToggleSets = "trytogglesets";
			public const string TryToggleStatus = "trytogglestatus";
			public const string UILanguageId = "uilanguageid";
			public const string UseCrmFormForAppointment = "usecrmformforappointment";
			public const string UseCrmFormForContact = "usecrmformforcontact";
			public const string UseCrmFormForEmail = "usecrmformforemail";
			public const string UseCrmFormForTask = "usecrmformfortask";
			public const string UseImageStrips = "useimagestrips";
			public const string UserProfile = "userprofile";
			public const string VersionNumber = "versionnumber";
			public const string VisualizationPaneLayout = "visualizationpanelayout";
			public const string WorkdayStartTime = "workdaystarttime";
			public const string WorkdayStopTime = "workdaystoptime";
			public const string business_unit_user_settings = "business_unit_user_settings";
			public const string lk_usersettings_createdonbehalfby = "lk_usersettings_createdonbehalfby";
			public const string lk_usersettings_modifiedonbehalfby = "lk_usersettings_modifiedonbehalfby";
			public const string lk_usersettingsbase_createdby = "lk_usersettingsbase_createdby";
			public const string lk_usersettingsbase_modifiedby = "lk_usersettingsbase_modifiedby";
			public const string user_settings = "user_settings";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public UserSettings() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "usersettings";
		
		public const string EntityLogicalCollectionName = "usersettingses";
		
		public const string EntitySetName = "usersettingscollection";
		
		/// <summary>
		/// Frequência de sondagem normal usada para sincronização do catálogo de endereços no Microsoft Office Outlook.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("addressbooksyncinterval")]
		public System.Nullable<int> AddressBookSyncInterval
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("addressbooksyncinterval");
			}
			set
			{
				this.SetAttributeValue("addressbooksyncinterval", value);
			}
		}
		
		/// <summary>
		/// Modo padrão (simples ou detalhado) da localização avançada.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("advancedfindstartupmode")]
		public System.Nullable<int> AdvancedFindStartupMode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("advancedfindstartupmode");
			}
			set
			{
				this.SetAttributeValue("advancedfindstartupmode", value);
			}
		}
		
		/// <summary>
		/// Este atributo não é mais usado. Os dados estão agora no atributo Mailbox.AllowEmailConnectorToUseCredentials.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("allowemailcredentials")]
		[System.ObsoleteAttribute()]
		public System.Nullable<bool> AllowEmailCredentials
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("allowemailcredentials");
			}
		}
		
		/// <summary>
		/// Designador AM a ser usado no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amdesignator")]
		public string AMDesignator
		{
			get
			{
				return this.GetAttributeValue<string>("amdesignator");
			}
			set
			{
				this.SetAttributeValue("amdesignator", value);
			}
		}
		
		/// <summary>
		/// Definir status do usuário para Sugestões de ADC
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocaptureuserstatus")]
		public System.Nullable<int> AutoCaptureUserStatus
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("autocaptureuserstatus");
			}
			set
			{
				this.SetAttributeValue("autocaptureuserstatus", value);
			}
		}
		
		/// <summary>
		/// Criar automaticamente contato na promoção do cliente
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocreatecontactonpromote")]
		public System.Nullable<int> AutoCreateContactOnPromote
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("autocreatecontactonpromote");
			}
			set
			{
				this.SetAttributeValue("autocreatecontactonpromote", value);
			}
		}
		
		/// <summary>
		/// Identificador exclusivo da unidade de negócios à qual o usuário está associado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("businessunitid")]
		public System.Nullable<System.Guid> BusinessUnitId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("businessunitid");
			}
			set
			{
				this.SetAttributeValue("businessunitid", value);
			}
		}
		
		/// <summary>
		/// Tipo de calendário do sistema. Por padrão, definido como Gregoriano (EUA).
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("calendartype")]
		public System.Nullable<int> CalendarType
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("calendartype");
			}
			set
			{
				this.SetAttributeValue("calendartype", value);
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário que criou as configurações de usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Data e hora em que o objeto de configurações de usuário foi criado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário delegado que criou o usersettings.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Número de casas decimais que podem ser usadas para a moeda.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("currencydecimalprecision")]
		[System.ObsoleteAttribute()]
		public System.Nullable<int> CurrencyDecimalPrecision
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("currencydecimalprecision");
			}
			set
			{
				this.SetAttributeValue("currencydecimalprecision", value);
			}
		}
		
		/// <summary>
		/// Informações sobre como os símbolos de moeda são colocados no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("currencyformatcode")]
		public System.Nullable<int> CurrencyFormatCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("currencyformatcode");
			}
			set
			{
				this.SetAttributeValue("currencyformatcode", value);
			}
		}
		
		/// <summary>
		/// Símbolo usado para moeda no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("currencysymbol")]
		public string CurrencySymbol
		{
			get
			{
				return this.GetAttributeValue<string>("currencysymbol");
			}
			set
			{
				this.SetAttributeValue("currencysymbol", value);
			}
		}
		
		/// <summary>
		/// Determina se o status da tentativa de instalação automática do Dynamics 365 para Teams foi concluída
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("d365autoinstallattemptstatus")]
		public virtual usersettings_d365autoinstallattemptstatus? D365AutoInstallAttemptStatus
		{
			get
			{
				return ((usersettings_d365autoinstallattemptstatus?)(EntityOptionSetEnum.GetEnum(this, "d365autoinstallattemptstatus")));
			}
			set
			{
				this.SetAttributeValue("d365autoinstallattemptstatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Informação que especifica o nível de validação de dados em planilhas do Excel exportada em um formato adequado para importação.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("datavalidationmodeforexporttoexcel")]
		public virtual usersettings_datavalidationmodeforexporttoexcel? DataValidationModeForExportToExcel
		{
			get
			{
				return ((usersettings_datavalidationmodeforexporttoexcel?)(EntityOptionSetEnum.GetEnum(this, "datavalidationmodeforexporttoexcel")));
			}
			set
			{
				this.SetAttributeValue("datavalidationmodeforexporttoexcel", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Informações sobre o modo de exibição de data no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dateformatcode")]
		public System.Nullable<int> DateFormatCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("dateformatcode");
			}
			set
			{
				this.SetAttributeValue("dateformatcode", value);
			}
		}
		
		/// <summary>
		/// Cadeia de caracteres mostrando como a data é exibida no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dateformatstring")]
		public string DateFormatString
		{
			get
			{
				return this.GetAttributeValue<string>("dateformatstring");
			}
			set
			{
				this.SetAttributeValue("dateformatstring", value);
			}
		}
		
		/// <summary>
		/// Caractere usado para separar mês, dia e ano em datas do Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dateseparator")]
		public string DateSeparator
		{
			get
			{
				return this.GetAttributeValue<string>("dateseparator");
			}
			set
			{
				this.SetAttributeValue("dateseparator", value);
			}
		}
		
		/// <summary>
		/// Símbolo usado em casas decimais no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("decimalsymbol")]
		public string DecimalSymbol
		{
			get
			{
				return this.GetAttributeValue<string>("decimalsymbol");
			}
			set
			{
				this.SetAttributeValue("decimalsymbol", value);
			}
		}
		
		/// <summary>
		/// Modo de exibição de calendário padrão do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultcalendarview")]
		public System.Nullable<int> DefaultCalendarView
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("defaultcalendarview");
			}
			set
			{
				this.SetAttributeValue("defaultcalendarview", value);
			}
		}
		
		/// <summary>
		/// Área de texto para inserir código de país padrão.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultcountrycode")]
		public string DefaultCountryCode
		{
			get
			{
				return this.GetAttributeValue<string>("defaultcountrycode");
			}
			set
			{
				this.SetAttributeValue("defaultcountrycode", value);
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do painel padrão.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultdashboardid")]
		public System.Nullable<System.Guid> DefaultDashboardId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("defaultdashboardid");
			}
			set
			{
				this.SetAttributeValue("defaultdashboardid", value);
			}
		}
		
		/// <summary>
		/// Experiência de pesquisa padrão para o usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultsearchexperience")]
		public virtual usersettings_defaultsearchexperience? DefaultSearchExperience
		{
			get
			{
				return ((usersettings_defaultsearchexperience?)(EntityOptionSetEnum.GetEnum(this, "defaultsearchexperience")));
			}
			set
			{
				this.SetAttributeValue("defaultsearchexperience", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Este atributo não é mais usado. Os dados estão agora no atributo Mailbox.Password.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailpassword")]
		[System.ObsoleteAttribute()]
		public string EmailPassword
		{
			get
			{
				return this.GetAttributeValue<string>("emailpassword");
			}
		}
		
		/// <summary>
		/// Este atributo não é mais usado. Os dados estão agora no atributo Mailbox.UserName.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailusername")]
		[System.ObsoleteAttribute()]
		public string EmailUsername
		{
			get
			{
				return this.GetAttributeValue<string>("emailusername");
			}
		}
		
		/// <summary>
		/// Indica o modo de formulário a ser usado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityformmode")]
		public virtual usersettings_entityformmode? EntityFormMode
		{
			get
			{
				return ((usersettings_entityformmode?)(EntityOptionSetEnum.GetEnum(this, "entityformmode")));
			}
			set
			{
				this.SetAttributeValue("entityformmode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Ordem na qual os nomes devem ser exibidos no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("fullnameconventioncode")]
		public System.Nullable<int> FullNameConventionCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("fullnameconventioncode");
			}
			set
			{
				this.SetAttributeValue("fullnameconventioncode", value);
			}
		}
		
		/// <summary>
		/// Informação que especifica se o painel Introdução está habilitado em listas.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("getstartedpanecontentenabled")]
		public System.Nullable<bool> GetStartedPaneContentEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("getstartedpanecontentenabled");
			}
			set
			{
				this.SetAttributeValue("getstartedpanecontentenabled", value);
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do idioma da Ajuda.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("helplanguageid")]
		public System.Nullable<int> HelpLanguageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("helplanguageid");
			}
			set
			{
				this.SetAttributeValue("helplanguageid", value);
			}
		}
		
		/// <summary>
		/// Home page do site para o usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("homepagearea")]
		public string HomepageArea
		{
			get
			{
				return this.GetAttributeValue<string>("homepagearea");
			}
			set
			{
				this.SetAttributeValue("homepagearea", value);
			}
		}
		
		/// <summary>
		/// Configuração do layout da página inicial.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("homepagelayout")]
		public string HomepageLayout
		{
			get
			{
				return this.GetAttributeValue<string>("homepagelayout");
			}
			set
			{
				this.SetAttributeValue("homepagelayout", value);
			}
		}
		
		/// <summary>
		/// Página do site para o usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("homepagesubarea")]
		public string HomepageSubarea
		{
			get
			{
				return this.GetAttributeValue<string>("homepagesubarea");
			}
			set
			{
				this.SetAttributeValue("homepagesubarea", value);
			}
		}
		
		/// <summary>
		/// Informações que especificam se uma conta de usuário deve ignorar emails não solicitados (obsoletos).
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ignoreunsolicitedemail")]
		public System.Nullable<bool> IgnoreUnsolicitedEmail
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ignoreunsolicitedemail");
			}
			set
			{
				this.SetAttributeValue("ignoreunsolicitedemail", value);
			}
		}
		
		/// <summary>
		/// Método de filtragem de emails de entrada.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("incomingemailfilteringmethod")]
		public virtual usersettings_incomingemailfilteringmethod? IncomingEmailFilteringMethod
		{
			get
			{
				return ((usersettings_incomingemailfilteringmethod?)(EntityOptionSetEnum.GetEnum(this, "incomingemailfilteringmethod")));
			}
			set
			{
				this.SetAttributeValue("incomingemailfilteringmethod", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Mostra ou descarta o alerta de Aplicativos para Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isappsforcrmalertdismissed")]
		public System.Nullable<bool> IsAppsForCrmAlertDismissed
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isappsforcrmalertdismissed");
			}
			set
			{
				this.SetAttributeValue("isappsforcrmalertdismissed", value);
			}
		}
		
		/// <summary>
		/// Indica se o recurso Captura Automática será usado habilitado ou não.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isautodatacaptureenabled")]
		public System.Nullable<bool> IsAutoDataCaptureEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isautodatacaptureenabled");
			}
			set
			{
				this.SetAttributeValue("isautodatacaptureenabled", value);
			}
		}
		
		/// <summary>
		/// Habilitar ou desabilitar seleção do código de país.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isdefaultcountrycodecheckenabled")]
		public System.Nullable<bool> IsDefaultCountryCodeCheckEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isdefaultcountrycodecheckenabled");
			}
			set
			{
				this.SetAttributeValue("isdefaultcountrycodecheckenabled", value);
			}
		}
		
		/// <summary>
		/// Indica se a detecção de duplicidade é habilitada ao entrar online.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isduplicatedetectionenabledwhengoingonline")]
		public System.Nullable<bool> IsDuplicateDetectionEnabledWhenGoingOnline
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isduplicatedetectionenabledwhengoingonline");
			}
			set
			{
				this.SetAttributeValue("isduplicatedetectionenabledwhengoingonline", value);
			}
		}
		
		/// <summary>
		/// Habilitar ou desabilitar o modo de exibição de conversa do email na seleção do mural da linha do tempo.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isemailconversationviewenabled")]
		public System.Nullable<bool> IsEmailConversationViewEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isemailconversationviewenabled");
			}
			set
			{
				this.SetAttributeValue("isemailconversationviewenabled", value);
			}
		}
		
		/// <summary>
		/// Habilitar ou desabilitar a ajuda guiada.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isguidedhelpenabled")]
		public System.Nullable<bool> IsGuidedHelpEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isguidedhelpenabled");
			}
			set
			{
				this.SetAttributeValue("isguidedhelpenabled", value);
			}
		}
		
		/// <summary>
		/// Indica se a sincronização da reserva de recursos do usuário com o Exchange é habilitada no nível do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isresourcebookingexchangesyncenabled")]
		public System.Nullable<bool> IsResourceBookingExchangeSyncEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isresourcebookingexchangesyncenabled");
			}
			set
			{
				this.SetAttributeValue("isresourcebookingexchangesyncenabled", value);
			}
		}
		
		/// <summary>
		/// Indica se o privilégio enviar como outro usuário está habilitado ou não.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("issendasallowed")]
		public System.Nullable<bool> IsSendAsAllowed
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("issendasallowed");
			}
			set
			{
				this.SetAttributeValue("issendasallowed", value);
			}
		}
		
		/// <summary>
		/// Mostra a última vez que os rastreamentos foram lidos no banco de dados.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lastalertsviewedtime")]
		public System.Nullable<System.DateTime> LastAlertsViewedTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("lastalertsviewedtime");
			}
			set
			{
				this.SetAttributeValue("lastalertsviewedtime", value);
			}
		}
		
		/// <summary>
		/// Armazena o carimbo de data/hora de quando o atributo ViewPersonalizationSettings foi atualizado para esse usuário na tabela UserEntityUISettings.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lastmodifiedtimeforviewpersonalizationsettings")]
		public System.Nullable<System.DateTime> LastModifiedTimeForViewPersonalizationSettings
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("lastmodifiedtimeforviewpersonalizationsettings");
			}
			set
			{
				this.SetAttributeValue("lastmodifiedtimeforviewpersonalizationsettings", value);
			}
		}
		
		/// <summary>
		/// Identificador exclusivo da localidade do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("localeid")]
		public System.Nullable<int> LocaleId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("localeid");
			}
			set
			{
				this.SetAttributeValue("localeid", value);
			}
		}
		
		/// <summary>
		/// Informação que especifica como a Data por Extenso é exibida no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("longdateformatcode")]
		public System.Nullable<int> LongDateFormatCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("longdateformatcode");
			}
			set
			{
				this.SetAttributeValue("longdateformatcode", value);
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário que modificou por último as configurações de usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Data e hora da última modificação do objeto de configurações de usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário delegado que modificou o usersettings pela última vez.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Informação que especifica como os números negativos de moeda são exibidos no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("negativecurrencyformatcode")]
		public System.Nullable<int> NegativeCurrencyFormatCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("negativecurrencyformatcode");
			}
			set
			{
				this.SetAttributeValue("negativecurrencyformatcode", value);
			}
		}
		
		/// <summary>
		/// Informação que especifica como os números negativos são exibidos no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("negativeformatcode")]
		public System.Nullable<int> NegativeFormatCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("negativeformatcode");
			}
			set
			{
				this.SetAttributeValue("negativeformatcode", value);
			}
		}
		
		/// <summary>
		/// Próximo número de controle.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nexttrackingnumber")]
		public System.Nullable<int> NextTrackingNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("nexttrackingnumber");
			}
			set
			{
				this.SetAttributeValue("nexttrackingnumber", value);
			}
		}
		
		/// <summary>
		/// Informação que especifica como os números são agrupados no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("numbergroupformat")]
		public string NumberGroupFormat
		{
			get
			{
				return this.GetAttributeValue<string>("numbergroupformat");
			}
			set
			{
				this.SetAttributeValue("numbergroupformat", value);
			}
		}
		
		/// <summary>
		/// Símbolo usado para separação de números no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("numberseparator")]
		public string NumberSeparator
		{
			get
			{
				return this.GetAttributeValue<string>("numberseparator");
			}
			set
			{
				this.SetAttributeValue("numberseparator", value);
			}
		}
		
		/// <summary>
		/// Frequência de sondagem normal usada para sincronização offline em segundo plano no Microsoft Office Outlook.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("offlinesyncinterval")]
		public System.Nullable<int> OfflineSyncInterval
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("offlinesyncinterval");
			}
			set
			{
				this.SetAttributeValue("offlinesyncinterval", value);
			}
		}
		
		/// <summary>
		/// Frequência de pesquisa normal usada na sincronização de registros no Microsoft Office Outlook.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("outlooksyncinterval")]
		public System.Nullable<int> OutlookSyncInterval
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("outlooksyncinterval");
			}
			set
			{
				this.SetAttributeValue("outlooksyncinterval", value);
			}
		}
		
		/// <summary>
		/// Informação que especifica o número de itens a serem listados em uma página no modo de exibição de lista.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("paginglimit")]
		public System.Nullable<int> PagingLimit
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("paginglimit");
			}
			set
			{
				this.SetAttributeValue("paginglimit", value);
			}
		}
		
		/// <summary>
		/// Apenas para uso interno.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("personalizationsettings")]
		public string PersonalizationSettings
		{
			get
			{
				return this.GetAttributeValue<string>("personalizationsettings");
			}
			set
			{
				this.SetAttributeValue("personalizationsettings", value);
			}
		}
		
		/// <summary>
		/// Designador PM a ser usado no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pmdesignator")]
		public string PMDesignator
		{
			get
			{
				return this.GetAttributeValue<string>("pmdesignator");
			}
			set
			{
				this.SetAttributeValue("pmdesignator", value);
			}
		}
		
		/// <summary>
		/// Preferred Solution when create a component without under a solution in this organization
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("preferredsolution")]
		public Microsoft.Xrm.Sdk.EntityReference PreferredSolution
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("preferredsolution");
			}
			set
			{
				this.SetAttributeValue("preferredsolution", value);
			}
		}
		
		/// <summary>
		/// Número de casas decimais que podem ser usadas em preços.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pricingdecimalprecision")]
		[System.ObsoleteAttribute()]
		public System.Nullable<int> PricingDecimalPrecision
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("pricingdecimalprecision");
			}
			set
			{
				this.SetAttributeValue("pricingdecimalprecision", value);
			}
		}
		
		/// <summary>
		/// Substituição de canal do aplicativo de modelo
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("releasechannel")]
		public virtual usersettings_releasechannel? ReleaseChannel
		{
			get
			{
				return ((usersettings_releasechannel?)(EntityOptionSetEnum.GetEnum(this, "releasechannel")));
			}
			set
			{
				this.SetAttributeValue("releasechannel", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Lista de opções para selecionar a preferência do usuário ao informar erros de script.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("reportscripterrors")]
		public virtual usersettings_reportscripterrors? ReportScriptErrors
		{
			get
			{
				return ((usersettings_reportscripterrors?)(EntityOptionSetEnum.GetEnum(this, "reportscripterrors")));
			}
			set
			{
				this.SetAttributeValue("reportscripterrors", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// O número da versão da sincronização de reservas de recursos com o Exchange.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("resourcebookingexchangesyncversion")]
		public System.Nullable<long> ResourceBookingExchangeSyncVersion
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("resourcebookingexchangesyncversion");
			}
			set
			{
				this.SetAttributeValue("resourcebookingexchangesyncversion", value);
			}
		}
		
		/// <summary>
		/// Armazena a ID do filtro salvo do painel de hub do SAC selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("selectedglobalfilterid")]
		public System.Nullable<System.Guid> SelectedGlobalFilterId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("selectedglobalfilterid");
			}
			set
			{
				this.SetAttributeValue("selectedglobalfilterid", value);
			}
		}
		
		/// <summary>
		/// Informação que especifica se o número da semana deve ser mostrado em exibições de calendário no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("showweeknumber")]
		public System.Nullable<bool> ShowWeekNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("showweeknumber");
			}
			set
			{
				this.SetAttributeValue("showweeknumber", value);
			}
		}
		
		/// <summary>
		/// Somente para uso Interno
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("splitviewstate")]
		public System.Nullable<bool> SplitViewState
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("splitviewstate");
			}
			set
			{
				this.SetAttributeValue("splitviewstate", value);
			}
		}
		
		/// <summary>
		/// Indica se o campo da empresa nos itens do Outlook é definido durante a sincronização do programa.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("synccontactcompany")]
		public System.Nullable<bool> SyncContactCompany
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("synccontactcompany");
			}
			set
			{
				this.SetAttributeValue("synccontactcompany", value);
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("systemuserid")]
		public System.Nullable<System.Guid> SystemUserId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("systemuserid");
			}
			set
			{
				this.SetAttributeValue("systemuserid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("systemuserid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.SystemUserId = value;
			}
		}
		
		/// <summary>
		/// O número de vezes que um usuário interagiu com a bolha explicativa de recursos de pesquisa do Dataverse com Escopo em Tabela.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("tablescopeddvsearchfeatureteachingbubbleviews")]
		public System.Nullable<int> TableScopedDVSearchFeatureTeachingBubbleViews
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("tablescopeddvsearchfeatureteachingbubbleviews");
			}
			set
			{
				this.SetAttributeValue("tablescopeddvsearchfeatureteachingbubbleviews", value);
			}
		}
		
		/// <summary>
		/// O número de vezes que um usuário interagiu com a bolha explicativa de Localização Rápida de pesquisa do Dataverse com Escopo em Tabela.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("tablescopeddvsearchquickfindteachingbubbleviews")]
		public System.Nullable<int> TableScopedDVSearchQuickFindTeachingBubbleViews
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("tablescopeddvsearchquickfindteachingbubbleviews");
			}
			set
			{
				this.SetAttributeValue("tablescopeddvsearchquickfindteachingbubbleviews", value);
			}
		}
		
		/// <summary>
		/// Informação que especifica como a hora é exibida no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timeformatcode")]
		public System.Nullable<int> TimeFormatCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timeformatcode");
			}
			set
			{
				this.SetAttributeValue("timeformatcode", value);
			}
		}
		
		/// <summary>
		/// Texto do modo de exibição de hora no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timeformatstring")]
		public string TimeFormatString
		{
			get
			{
				return this.GetAttributeValue<string>("timeformatstring");
			}
			set
			{
				this.SetAttributeValue("timeformatstring", value);
			}
		}
		
		/// <summary>
		/// Texto do modo de exibição de hora no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timeseparator")]
		public string TimeSeparator
		{
			get
			{
				return this.GetAttributeValue<string>("timeseparator");
			}
			set
			{
				this.SetAttributeValue("timeseparator", value);
			}
		}
		
		/// <summary>
		/// Ajuste do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonebias")]
		public System.Nullable<int> TimeZoneBias
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonebias");
			}
			set
			{
				this.SetAttributeValue("timezonebias", value);
			}
		}
		
		/// <summary>
		/// Fuso horário local do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonecode")]
		public System.Nullable<int> TimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonecode");
			}
			set
			{
				this.SetAttributeValue("timezonecode", value);
			}
		}
		
		/// <summary>
		/// Ajuste do horário de verão do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylightbias")]
		public System.Nullable<int> TimeZoneDaylightBias
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylightbias");
			}
			set
			{
				this.SetAttributeValue("timezonedaylightbias", value);
			}
		}
		
		/// <summary>
		/// Dia do horário de verão do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylightday")]
		public System.Nullable<int> TimeZoneDaylightDay
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylightday");
			}
			set
			{
				this.SetAttributeValue("timezonedaylightday", value);
			}
		}
		
		/// <summary>
		/// Dia da semana do horário de verão do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylightdayofweek")]
		public System.Nullable<int> TimeZoneDaylightDayOfWeek
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylightdayofweek");
			}
			set
			{
				this.SetAttributeValue("timezonedaylightdayofweek", value);
			}
		}
		
		/// <summary>
		/// Hora do horário de verão do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylighthour")]
		public System.Nullable<int> TimeZoneDaylightHour
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylighthour");
			}
			set
			{
				this.SetAttributeValue("timezonedaylighthour", value);
			}
		}
		
		/// <summary>
		/// Minuto do horário de verão do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylightminute")]
		public System.Nullable<int> TimeZoneDaylightMinute
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylightminute");
			}
			set
			{
				this.SetAttributeValue("timezonedaylightminute", value);
			}
		}
		
		/// <summary>
		/// Mês do horário de verão do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylightmonth")]
		public System.Nullable<int> TimeZoneDaylightMonth
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylightmonth");
			}
			set
			{
				this.SetAttributeValue("timezonedaylightmonth", value);
			}
		}
		
		/// <summary>
		/// Segundo do horário de verão do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylightsecond")]
		public System.Nullable<int> TimeZoneDaylightSecond
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylightsecond");
			}
			set
			{
				this.SetAttributeValue("timezonedaylightsecond", value);
			}
		}
		
		/// <summary>
		/// Ano do horário de verão do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylightyear")]
		public System.Nullable<int> TimeZoneDaylightYear
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylightyear");
			}
			set
			{
				this.SetAttributeValue("timezonedaylightyear", value);
			}
		}
		
		/// <summary>
		/// Diferença do horário oficial do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandardbias")]
		public System.Nullable<int> TimeZoneStandardBias
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandardbias");
			}
			set
			{
				this.SetAttributeValue("timezonestandardbias", value);
			}
		}
		
		/// <summary>
		/// Dia oficial do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandardday")]
		public System.Nullable<int> TimeZoneStandardDay
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandardday");
			}
			set
			{
				this.SetAttributeValue("timezonestandardday", value);
			}
		}
		
		/// <summary>
		/// Dia da semana oficial do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandarddayofweek")]
		public System.Nullable<int> TimeZoneStandardDayOfWeek
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandarddayofweek");
			}
			set
			{
				this.SetAttributeValue("timezonestandarddayofweek", value);
			}
		}
		
		/// <summary>
		/// Hora oficial do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandardhour")]
		public System.Nullable<int> TimeZoneStandardHour
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandardhour");
			}
			set
			{
				this.SetAttributeValue("timezonestandardhour", value);
			}
		}
		
		/// <summary>
		/// Minuto oficial do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandardminute")]
		public System.Nullable<int> TimeZoneStandardMinute
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandardminute");
			}
			set
			{
				this.SetAttributeValue("timezonestandardminute", value);
			}
		}
		
		/// <summary>
		/// Mês oficial do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandardmonth")]
		public System.Nullable<int> TimeZoneStandardMonth
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandardmonth");
			}
			set
			{
				this.SetAttributeValue("timezonestandardmonth", value);
			}
		}
		
		/// <summary>
		/// Segundo oficial do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandardsecond")]
		public System.Nullable<int> TimeZoneStandardSecond
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandardsecond");
			}
			set
			{
				this.SetAttributeValue("timezonestandardsecond", value);
			}
		}
		
		/// <summary>
		/// Ano oficial do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandardyear")]
		public System.Nullable<int> TimeZoneStandardYear
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandardyear");
			}
			set
			{
				this.SetAttributeValue("timezonestandardyear", value);
			}
		}
		
		/// <summary>
		/// ID de token de controle.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("trackingtokenid")]
		public System.Nullable<int> TrackingTokenId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("trackingtokenid");
			}
			set
			{
				this.SetAttributeValue("trackingtokenid", value);
			}
		}
		
		/// <summary>
		/// Identificador exclusivo da moeda padrão do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.SetAttributeValue("transactioncurrencyid", value);
			}
		}
		
		/// <summary>
		/// A lista de módulos do aplicativo com conjuntos de opções de tentativa
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("trytogglesets")]
		public string TryToggleSets
		{
			get
			{
				return this.GetAttributeValue<string>("trytogglesets");
			}
			set
			{
				this.SetAttributeValue("trytogglesets", value);
			}
		}
		
		/// <summary>
		/// Habilite ou desabilite a tentativa de alternar o status.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("trytogglestatus")]
		public System.Nullable<bool> TryToggleStatus
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("trytogglestatus");
			}
			set
			{
				this.SetAttributeValue("trytogglestatus", value);
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do idioma no qual a interface do usuário é exibida.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uilanguageid")]
		public System.Nullable<int> UILanguageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("uilanguageid");
			}
			set
			{
				this.SetAttributeValue("uilanguageid", value);
			}
		}
		
		/// <summary>
		/// Indica se o formulário de compromisso do Microsoft Dynamics 365 no Microsoft Office Outlook deve ser usado para criar novos compromissos.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("usecrmformforappointment")]
		public System.Nullable<bool> UseCrmFormForAppointment
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("usecrmformforappointment");
			}
			set
			{
				this.SetAttributeValue("usecrmformforappointment", value);
			}
		}
		
		/// <summary>
		/// Indica se o formulário de contatos do Microsoft Dynamics 365 no Microsoft Office Outlook deve ser usado para criar novos contatos.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("usecrmformforcontact")]
		public System.Nullable<bool> UseCrmFormForContact
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("usecrmformforcontact");
			}
			set
			{
				this.SetAttributeValue("usecrmformforcontact", value);
			}
		}
		
		/// <summary>
		/// Indica se o formulário de email do Microsoft Dynamics 365 no Microsoft Office Outlook deve ser usado para criar novos emails.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("usecrmformforemail")]
		public System.Nullable<bool> UseCrmFormForEmail
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("usecrmformforemail");
			}
			set
			{
				this.SetAttributeValue("usecrmformforemail", value);
			}
		}
		
		/// <summary>
		/// Indica se o formulário de tarefa do Microsoft Dynamics 365 no Microsoft Office Outlook deve ser usado para criar novas tarefas.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("usecrmformfortask")]
		public System.Nullable<bool> UseCrmFormForTask
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("usecrmformfortask");
			}
			set
			{
				this.SetAttributeValue("usecrmformfortask", value);
			}
		}
		
		/// <summary>
		/// Indica se faixas de imagem são usadas para processar imagens.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("useimagestrips")]
		public System.Nullable<bool> UseImageStrips
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("useimagestrips");
			}
			set
			{
				this.SetAttributeValue("useimagestrips", value);
			}
		}
		
		/// <summary>
		/// Especifica as IDs de perfil de usuário em uma lista separada por vírgula.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("userprofile")]
		public string UserProfile
		{
			get
			{
				return this.GetAttributeValue<string>("userprofile");
			}
			set
			{
				this.SetAttributeValue("userprofile", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// O layout do painel de visualização.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("visualizationpanelayout")]
		public virtual usersettings_visualizationpanelayout? VisualizationPaneLayout
		{
			get
			{
				return ((usersettings_visualizationpanelayout?)(EntityOptionSetEnum.GetEnum(this, "visualizationpanelayout")));
			}
			set
			{
				this.SetAttributeValue("visualizationpanelayout", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Hora de início do dia útil para o usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workdaystarttime")]
		public string WorkdayStartTime
		{
			get
			{
				return this.GetAttributeValue<string>("workdaystarttime");
			}
			set
			{
				this.SetAttributeValue("workdaystarttime", value);
			}
		}
		
		/// <summary>
		/// Hora de término do dia útil para o usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workdaystoptime")]
		public string WorkdayStopTime
		{
			get
			{
				return this.GetAttributeValue<string>("workdaystoptime");
			}
			set
			{
				this.SetAttributeValue("workdaystoptime", value);
			}
		}
		
		/// <summary>
		/// N:1 business_unit_user_settings
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("businessunitid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_user_settings")]
		public project_plugins.earlybound.BusinessUnit business_unit_user_settings
		{
			get
			{
				return this.GetRelatedEntity<project_plugins.earlybound.BusinessUnit>("business_unit_user_settings", null);
			}
			set
			{
				this.SetRelatedEntity<project_plugins.earlybound.BusinessUnit>("business_unit_user_settings", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_usersettings_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_usersettings_createdonbehalfby")]
		public project_plugins.earlybound.SystemUser lk_usersettings_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<project_plugins.earlybound.SystemUser>("lk_usersettings_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_usersettings_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_usersettings_modifiedonbehalfby")]
		public project_plugins.earlybound.SystemUser lk_usersettings_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<project_plugins.earlybound.SystemUser>("lk_usersettings_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_usersettingsbase_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_usersettingsbase_createdby")]
		public project_plugins.earlybound.SystemUser lk_usersettingsbase_createdby
		{
			get
			{
				return this.GetRelatedEntity<project_plugins.earlybound.SystemUser>("lk_usersettingsbase_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_usersettingsbase_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_usersettingsbase_modifiedby")]
		public project_plugins.earlybound.SystemUser lk_usersettingsbase_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<project_plugins.earlybound.SystemUser>("lk_usersettingsbase_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 user_settings
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("systemuserid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_settings")]
		public project_plugins.earlybound.SystemUser user_settings
		{
			get
			{
				return this.GetRelatedEntity<project_plugins.earlybound.SystemUser>("user_settings", null);
			}
			set
			{
				this.SetRelatedEntity<project_plugins.earlybound.SystemUser>("user_settings", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
