#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_plugins.earlybound
{
	
	
	/// <summary>
	/// O estado deste componente.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum componentstate
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Publicado = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Nopublicado = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Excludo = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExcluirNoPublicado = 3,
	}
}
#pragma warning restore CS1591
