#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_plugins.earlybound
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_opportunitygradeoptset
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ClassificaoA = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ClassificaoB = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ClassificaoC = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ClassificaoD = 3,
	}
}
#pragma warning restore CS1591
