#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_plugins.earlybound
{
	
	
	/// <summary>
	/// Samesite mode for Session Cookie: 0 is Default, 1 is None, 2 is Lax , 3 is Strict
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum organization_samesitemodeforsessioncookie
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Default = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Lax = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Strict = 3,
	}
}
#pragma warning restore CS1591
