#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_plugins.earlybound
{
	
	
	/// <summary>
	/// O tipo de Processo de Compra para este cliente potencial.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum purchaseprocess
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Individual = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Comisso = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Desconhecido = 2,
	}
}
#pragma warning restore CS1591
