#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_plugins.earlybound
{
	
	
	/// <summary>
	/// O período em que este cliente potencial provavelmente fará uma compra.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum purchasetimeframe
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Imediato = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EsteTrimestre = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PrximoTrimestre = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EsteAno = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Desconhecido = 4,
	}
}
#pragma warning restore CS1591
