#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_plugins.earlybound
{
	
	
	/// <summary>
	/// Especifica se a propriedade está no modo Editar ou Retificar.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum qooiproduct_propertiesconfigurationstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Editar = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Retificar = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoConfigurado = 2,
	}
}
#pragma warning restore CS1591
