#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_plugins.earlybound
{
	
	
	/// <summary>
	/// Código de erro de preços.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum qooi_pricingerrorcode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Nenhum = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ErrodeDetalhe = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FaltaoNveldePreo = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NveldePreoInativo = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FaltaaQuantidade = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FaltaoPreoUnitrio = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FaltaoProduto = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProdutoInvlido = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FaltaoCdigodePrecificao = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CdigodePrecificaoInvlido = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FaltaaUM = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProdutoNoEstnoNveldePreo = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FaltaoValordoNveldePreo = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FaltaaPorcentagemdoNveldePreo = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FaltaoPreo = 14,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FaltaoCustoAtual = 15,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FaltaoCustoPadro = 16,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ValorInvlidodeNveldePreo = 17,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PorcentagemInvlidadeNveldePreo = 18,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PreoInvlido = 19,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustoAtualInvlido = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustoPadroInvlido = 21,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PolticadeArredondamentoInvlida = 22,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpodeArredondamentoInvlida = 23,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ValorInvlidodeArredondamento = 24,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ErrodeClculodePreo = 25,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TipoInvlidodeDesconto = 26,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EstadoInvlidodoTipodeDesconto = 27,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DescontoInvlido = 28,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuantidadeInvlida = 29,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PrecisoInvlidadePrecificao = 30,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FaltaaUMPadrodoProduto = 31,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FaltaaProgramaodeUMdeProduto = 32,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TipodeDescontoInativo = 33,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MoedaInvlidadeNveldePreo = 34,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AtributodePreoForadeIntervalo = 35,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EstourodoAtributodeMoedaBase = 36,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EstouroNegativodoAtributodeMoedaBase = 37,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Amoedadatransaonoestdefinidaparaoitemdalistadepreosdoproduto = 38,
	}
}
#pragma warning restore CS1591
