#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_plugins.earlybound
{
	
	
	/// <summary>
	/// Código do Tipo de Produto
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum qooiproduct_producttype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Produto = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pacote = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProdutoObrigatriodoPacote = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProdutoOpcionaldoPacote = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Serviobaseadoemprojetos = 5,
	}
}
#pragma warning restore CS1591
