#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_plugins.earlybound
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum quotecreationmethod
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Desconhecido_a = 776160000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reviso = 776160001,
	}
}
#pragma warning restore CS1591
