#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_plugins.earlybound
{
	
	
	/// <summary>
	/// Valor indicando se o direito de acesso é atribuído automaticamente com base na licença do usuário
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum securityrole_isautoassigned
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		No = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sim = 1,
	}
}
#pragma warning restore CS1591
