#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_plugins.earlybound
{
	
	
	/// <summary>
	/// Opções para Exibição Padrão do Modelo
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum templatedefaultview
	{
		
		/// <summary>
		/// Exibição de Blocos
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExibiodeBlocos = 1,
		
		/// <summary>
		/// Exibição de Grade
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExibiodeGrade = 2,
		
		/// <summary>
		/// Exibição de Lista
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExibiodeLista = 3,
	}
}
#pragma warning restore CS1591
