#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace project_plugins.earlybound
{


    /// <summary>
    /// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
    /// </summary>
    public partial class CrmServiceContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
    {

        /// <summary>
        /// Constructor.
        /// </summary>
        public CrmServiceContext(Microsoft.Xrm.Sdk.IOrganizationService service) :
                base(service)
        {
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="project_plugins.earlybound.SystemUser"/> entities.
        /// </summary>
        public System.Linq.IQueryable<project_plugins.earlybound.SystemUser> SystemUserSet
        {
            get
            {
                return this.CreateQuery<project_plugins.earlybound.SystemUser>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="project_plugins.earlybound.Team"/> entities.
        /// </summary>
        public System.Linq.IQueryable<project_plugins.earlybound.Team> TeamSet
        {
            get
            {
                return this.CreateQuery<project_plugins.earlybound.Team>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="project_plugins.earlybound.BusinessUnit"/> entities.
        /// </summary>
        public System.Linq.IQueryable<project_plugins.earlybound.BusinessUnit> BusinessUnitSet
        {
            get
            {
                return this.CreateQuery<project_plugins.earlybound.BusinessUnit>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="project_plugins.earlybound.Role"/> entities.
        /// </summary>
        public System.Linq.IQueryable<project_plugins.earlybound.Role> RoleSet
        {
            get
            {
                return this.CreateQuery<project_plugins.earlybound.Role>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="project_plugins.earlybound.SystemUserRoles"/> entities.
        /// </summary>
        public System.Linq.IQueryable<project_plugins.earlybound.SystemUserRoles> SystemUserRolesSet
        {
            get
            {
                return this.CreateQuery<project_plugins.earlybound.SystemUserRoles>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="project_plugins.earlybound.TeamMembership"/> entities.
        /// </summary>
        public System.Linq.IQueryable<project_plugins.earlybound.TeamMembership> TeamMembershipSet
        {
            get
            {
                return this.CreateQuery<project_plugins.earlybound.TeamMembership>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="project_plugins.earlybound.TeamRoles"/> entities.
        /// </summary>
        public System.Linq.IQueryable<project_plugins.earlybound.TeamRoles> TeamRolesSet
        {
            get
            {
                return this.CreateQuery<project_plugins.earlybound.TeamRoles>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="project_plugins.earlybound.WebResource"/> entities.
        /// </summary>
        public System.Linq.IQueryable<project_plugins.earlybound.WebResource> WebResourceSet
        {
            get
            {
                return this.CreateQuery<project_plugins.earlybound.WebResource>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="project_plugins.earlybound.Organization"/> entities.
        /// </summary>
        public System.Linq.IQueryable<project_plugins.earlybound.Organization> OrganizationSet
        {
            get
            {
                return this.CreateQuery<project_plugins.earlybound.Organization>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="project_plugins.earlybound.UserSettings"/> entities.
        /// </summary>
        public System.Linq.IQueryable<project_plugins.earlybound.UserSettings> UserSettingsSet
        {
            get
            {
                return this.CreateQuery<project_plugins.earlybound.UserSettings>();
            }
        }


    }
}
#pragma warning restore CS1591
