#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_plugins.earlybound
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("AIClassify")]
	public partial class AIClassifyRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string[] Categories
		{
			get
			{
				if (this.Parameters.Contains("Categories"))
				{
					return ((string[])(this.Parameters["Categories"]));
				}
				else
				{
					return default(string[]);
				}
			}
			set
			{
				this.Parameters["Categories"] = value;
			}
		}
		
		public string Text
		{
			get
			{
				if (this.Parameters.Contains("Text"))
				{
					return ((string)(this.Parameters["Text"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Text"] = value;
			}
		}
		
		public bool AllowMultipleCategories
		{
			get
			{
				if (this.Parameters.Contains("AllowMultipleCategories"))
				{
					return ((bool)(this.Parameters["AllowMultipleCategories"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["AllowMultipleCategories"] = value;
			}
		}
		
		public AIClassifyRequest()
		{
			this.RequestName = "AIClassify";
			this.Categories = default(string[]);
			this.Text = default(string);
			this.AllowMultipleCategories = default(bool);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("AIClassify")]
	public partial class AIClassifyResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public AIClassifyResponse()
		{
		}
		
		public string Classification
		{
			get
			{
				if (this.Results.Contains("Classification"))
				{
					return ((string)(this.Results["Classification"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
