#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_plugins.earlybound
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("AIExtract")]
	public partial class AIExtractRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string Entity
		{
			get
			{
				if (this.Parameters.Contains("Entity"))
				{
					return ((string)(this.Parameters["Entity"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Entity"] = value;
			}
		}
		
		public string Text
		{
			get
			{
				if (this.Parameters.Contains("Text"))
				{
					return ((string)(this.Parameters["Text"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Text"] = value;
			}
		}
		
		public AIExtractRequest()
		{
			this.RequestName = "AIExtract";
			this.Entity = default(string);
			this.Text = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("AIExtract")]
	public partial class AIExtractResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public AIExtractResponse()
		{
		}
		
		public string[] ExtractedData
		{
			get
			{
				if (this.Results.Contains("ExtractedData"))
				{
					return ((string[])(this.Results["ExtractedData"]));
				}
				else
				{
					return default(string[]);
				}
			}
		}
	}
}
#pragma warning restore CS1591
