#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_plugins.earlybound
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("AISummarizeRecord")]
	public partial class AISummarizeRecordRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string RecordContext
		{
			get
			{
				if (this.Parameters.Contains("RecordContext"))
				{
					return ((string)(this.Parameters["RecordContext"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RecordContext"] = value;
			}
		}
		
		public bool IsMergedCatchupAndSummary
		{
			get
			{
				if (this.Parameters.Contains("IsMergedCatchupAndSummary"))
				{
					return ((bool)(this.Parameters["IsMergedCatchupAndSummary"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["IsMergedCatchupAndSummary"] = value;
			}
		}
		
		public string EntityLogicalName
		{
			get
			{
				if (this.Parameters.Contains("EntityLogicalName"))
				{
					return ((string)(this.Parameters["EntityLogicalName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntityLogicalName"] = value;
			}
		}
		
		public string Id
		{
			get
			{
				if (this.Parameters.Contains("Id"))
				{
					return ((string)(this.Parameters["Id"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Id"] = value;
			}
		}
		
		public AISummarizeRecordRequest()
		{
			this.RequestName = "AISummarizeRecord";
			this.EntityLogicalName = default(string);
			this.Id = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("AISummarizeRecord")]
	public partial class AISummarizeRecordResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public AISummarizeRecordResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.Entity AdditionalInformation
		{
			get
			{
				if (this.Results.Contains("AdditionalInformation"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["AdditionalInformation"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
		}
		
		public string SummarizedText
		{
			get
			{
				if (this.Results.Contains("SummarizedText"))
				{
					return ((string)(this.Results["SummarizedText"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
