#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_plugins.earlybound
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("AITranslate")]
	public partial class AITranslateRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string TargetLanguage
		{
			get
			{
				if (this.Parameters.Contains("TargetLanguage"))
				{
					return ((string)(this.Parameters["TargetLanguage"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["TargetLanguage"] = value;
			}
		}
		
		public string Text
		{
			get
			{
				if (this.Parameters.Contains("Text"))
				{
					return ((string)(this.Parameters["Text"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Text"] = value;
			}
		}
		
		public AITranslateRequest()
		{
			this.RequestName = "AITranslate";
			this.Text = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("AITranslate")]
	public partial class AITranslateResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public AITranslateResponse()
		{
		}
		
		public string TranslatedText
		{
			get
			{
				if (this.Results.Contains("TranslatedText"))
				{
					return ((string)(this.Results["TranslatedText"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
